=== tylerm007/MetaRepos/Source/VLS/DataObjects/Validation/QueryObject.dtd
<!ELEMENT QueryObject ( DataObjects | Attributes | Joins | Where | OrderBy | GroupBy | Having | RuntimeSql |  Description | Comments | ExtendedProperties | HiddenProperties | RelsToChildDataObjects | RelsToParentDataObjects | PickSupportedRels )* >
<!ATTLIST QueryObject
	IsRemoteAccessible 	( True | False) #IMPLIED
	SqlTextModified		( True | False) #IMPLIED
	SqlDialect		(SQLStandard | Oracle | Sybase | Informix | ODBC | DB2UDB) #IMPLIED
	SuperClass		CDATA #IMPLIED
	SurrId			CDATA #IMPLIED
	ChildMostDataObject 	CDATA #IMPLIED
	DistinctRowsOnly	( True | False) #IMPLIED
	DeploySecurityInfo ( True | False) #IMPLIED
	DTDVersion		CDATA #REQUIRED
>

<!ELEMENT DataObjects (DataObject )*>
<!ELEMENT Attributes (Attribute )*>

<!ELEMENT Description (#PCDATA )>
<!ELEMENT Caption (#PCDATA )>
<!ELEMENT Comments (#PCDATA )>
<!ELEMENT Where (#PCDATA )>
<!ELEMENT OrderBy (OrderByAttribute)*>
<!ELEMENT GroupBy (GroupByAttribute)*>

<!ELEMENT Having (#PCDATA )>
<!ELEMENT RuntimeSql (#PCDATA )>
<!ELEMENT HiddenProperties (Property )* >
<!ELEMENT ExtendedProperties (Property )* >
<!ELEMENT Property EMPTY >
<!ATTLIST Property
	Name CDATA #REQUIRED
	Value CDATA #IMPLIED
>
<!ELEMENT GroupByAttribute EMPTY >
<!ATTLIST GroupByAttribute 
		Name CDATA #REQUIRED
>
<!ELEMENT OrderByAttribute EMPTY >
<!ATTLIST OrderByAttribute 
		Name CDATA #REQUIRED
		Direction (Ascending|Descending) #IMPLIED 
>

<!ELEMENT DataObject (Description )* >
<!ATTLIST DataObject
	DataObjectName CDATA #REQUIRED
	Alias CDATA #IMPLIED
>

<!ELEMENT Attribute (DataType | Formula | Description | Caption )* >
<!ATTLIST Attribute 
	Name CDATA #IMPLIED
	Alias CDATA #REQUIRED
	AggregationType ( None | Count | Max | Min | Sum | Avg) #IMPLIED 
	SourceDataObject CDATA #IMPLIED 
	Persistent	CDATA #IMPLIED
	InstanceOf  CDATA #IMPLIED
>
<!ELEMENT DataType EMPTY >
<!ATTLIST DataType 
	Type (Char |VarChar| Memo | Byte | Integer | Long | Double | Single | Decimal | Float | Date | Time | DateTime | Boolean | Currency | LongBinary) #REQUIRED 
	Size CDATA #IMPLIED
	Precision CDATA #IMPLIED
	Scale CDATA #IMPLIED
>

<!ELEMENT Formula (#PCDATA )>

<!ELEMENT Joins ( ColumnSet )* >
<!ATTLIST Joins 
	LeftDataObject CDATA #REQUIRED
	RightDataObject CDATA #REQUIRED
	JoinType ( Equal | Left | Right ) #IMPLIED
>

<!ELEMENT ColumnSet EMPTY >
<!ATTLIST ColumnSet 
	LeftAttribute CDATA #REQUIRED
	RightAttribute CDATA #REQUIRED
>


<!ELEMENT PickSupportedRels (PickSupportedRel)*>
<!ELEMENT PickSupportedRel EMPTY >
<!ATTLIST PickSupportedRel 
	PickSupportedRel CDATA #REQUIRED
>

<!ELEMENT RelsToChildDataObjects (RelToChildDO)*>
<!ELEMENT RelToChildDO (Aliases)>
<!ATTLIST RelToChildDO 
	RelToChildDO CDATA #REQUIRED
>

<!ELEMENT RelsToParentDataObjects (RelToParentDO)*>
<!ELEMENT RelToParentDO (Aliases)>
<!ATTLIST RelToParentDO 
	RelToParentDO CDATA #REQUIRED
>

<!ELEMENT Aliases (Alias)*>
<!ELEMENT Alias (AttributePairs)>
<!ATTLIST Alias
	Name CDATA #REQUIRED
>
<!ELEMENT AttributePairs (AttributePair)*>
<!ELEMENT AttributePair EMPTY >
<!ATTLIST AttributePair 
	ParentAttribute CDATA #REQUIRED
	ChildAttribute CDATA #REQUIRED
>

=== tylerm007/MetaRepos/Source/VLS/QueryObjects/Qry_AttrFormula.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE QueryObject SYSTEM "QueryObject.dtd">
<QueryObject
	SurrId="0414585975.tband.0002"
	IsRemoteAccessible="False"
	SqlDialect="SQLStandard"
	SuperClass="QueryObject"
	SqlTextModified="False"
	ChildMostDataObject="Attribute"
	DistinctRowsOnly="False"
	DeploySecurityInfo="False"
	DTDVersion="05.05.12"
	>
	<RuntimeSql><![CDATA[SELECT Attribute.AttrName AS AttrName, Attribute.Persistent AS Persistent, Attribute.ValueRequired AS ValueRequired, Attribute.DataType AS DataType, Attribute.AttrSize AS AttrSize, Attribute.Caption AS Caption, Derivation.Formula AS Formula, Attribute.Formula_Cnt AS Formula_Cnt, Attribute.RepositoryName AS RepositoryName, Attribute.DataObjectName AS DataObjectName FROM <dbschema>.Attribute Attribute, <dbschema>.Derivation Derivation  WHERE Derivation.RepositoryName = Attribute.RepositoryName  AND Derivation.DataObjectName = Attribute.DataObjectName  AND Derivation.AttrName = Attribute.AttrName  AND  Attribute.Formula_Cnt > 0   ORDER BY Attribute.AttrName Asc]]></RuntimeSql>
	<Where><![CDATA[Attribute.Formula_Cnt > 0]]></Where>
	<OrderBy>
	<OrderByAttribute
		Name="Attribute.AttrName"
		Direction="Ascending"
	/>
	</OrderBy>
	<Having><![CDATA[]]></Having>

	<DataObjects>
		<DataObject
			DataObjectName="Attribute"
			Alias="Attribute"
		/>

		<DataObject
			DataObjectName="Derivation"
			Alias="Derivation"
		/>

	</DataObjects>
	<Attributes>
		<Attribute
			Name="AttrName"
			Alias="AttrName"
			AggregationType="None"
			SourceDataObject="Attribute"
			Persistent="True"
		/>

		<Attribute
			Name="Persistent"
			Alias="Persistent"
			AggregationType="None"
			SourceDataObject="Attribute"
			Persistent="True"
		/>

		<Attribute
			Name="ValueRequired"
			Alias="ValueRequired"
			AggregationType="None"
			SourceDataObject="Attribute"
			Persistent="True"
		/>

		<Attribute
			Name="DataType"
			Alias="DataType"
			AggregationType="None"
			SourceDataObject="Attribute"
			Persistent="True"
		/>

		<Attribute
			Name="AttrSize"
			Alias="AttrSize"
			AggregationType="None"
			SourceDataObject="Attribute"
			Persistent="True"
			>
			<Caption><![CDATA[]]></Caption>
		</Attribute>

		<Attribute
			Name="Caption"
			Alias="Caption"
			AggregationType="None"
			SourceDataObject="Attribute"
			Persistent="True"
		/>

		<Attribute
			Name="Formula"
			Alias="Formula"
			AggregationType="None"
			SourceDataObject="Derivation"
			Persistent="True"
		/>

		<Attribute
			Name="Formula_Cnt"
			Alias="Formula_Cnt"
			AggregationType="None"
			SourceDataObject="Attribute"
			Persistent="True"
		/>

		<Attribute
			Name="RepositoryName"
			Alias="RepositoryName"
			AggregationType="None"
			SourceDataObject="Attribute"
			Persistent="True"
		/>

		<Attribute
			Name="DataObjectName"
			Alias="DataObjectName"
			AggregationType="None"
			SourceDataObject="Attribute"
			Persistent="True"
		/>

	</Attributes>
	<Joins
		LeftDataObject="Derivation"
		RightDataObject="ATTRIBUTE"
		JoinType="Equal"
		>
		<ColumnSet
			LeftAttribute="Derivation.RepositoryName"
			RightAttribute="Attribute.RepositoryName"
		/>
		<ColumnSet
			LeftAttribute="Derivation.DataObjectName"
			RightAttribute="Attribute.DataObjectName"
		/>
		<ColumnSet
			LeftAttribute="Derivation.AttrName"
			RightAttribute="Attribute.AttrName"
		/>
	</Joins>

	<RelsToParentDataObjects>
		<RelToParentDO
			RelToParentDO="DataObject(DataObject)-Attributes(Attribute)"
		>
			<Aliases>
				<Alias
					Name="Attribute"
				>
					<AttributePairs>
					<AttributePair
							ParentAttribute="RepositoryName"
							ChildAttribute="RepositoryName"
							/>
					<AttributePair
							ParentAttribute="DataObjectName"
							ChildAttribute="DataObjectName"
							/>
					</AttributePairs>
				</Alias>
			</Aliases>
		</RelToParentDO>
	</RelsToParentDataObjects>

	<RelsToChildDataObjects>
		<RelToChildDO
			RelToChildDO="DerivationAttr(Attribute)-Derivations(Derivation)"
		>
			<Aliases>
				<Alias
					Name="Attribute"
				>
					<AttributePairs>
				<AttributePair
							ParentAttribute="RepositoryName"
							ChildAttribute="RepositoryName"
							/>
				<AttributePair
							ParentAttribute="DataObjectName"
							ChildAttribute="DataObjectName"
							/>
				<AttributePair
							ParentAttribute="AttrName"
							ChildAttribute="AttrName"
							/>
					</AttributePairs>
				</Alias>
			</Aliases>
		</RelToChildDO>
		<RelToChildDO
			RelToChildDO="Attribute(Attribute)-Derivation(Derivation)"
		>
			<Aliases>
				<Alias
					Name="Attribute"
				>
					<AttributePairs>
				<AttributePair
							ParentAttribute="RepositoryName"
							ChildAttribute="RepositoryName"
							/>
				<AttributePair
							ParentAttribute="DataObjectName"
							ChildAttribute="SourceDataObject"
							/>
				<AttributePair
							ParentAttribute="AttrName"
							ChildAttribute="AttrName"
							/>
					</AttributePairs>
				</Alias>
			</Aliases>
		</RelToChildDO>
		<RelToChildDO
			RelToChildDO="Attribute1(Attribute)-IndexAttr(IndexAttr)"
		>
			<Aliases>
				<Alias
					Name="Attribute"
				>
					<AttributePairs>
				<AttributePair
							ParentAttribute="RepositoryName"
							ChildAttribute="RepositoryName"
							/>
				<AttributePair
							ParentAttribute="DataObjectName"
							ChildAttribute="DataObjectName"
							/>
				<AttributePair
							ParentAttribute="AttrName"
							ChildAttribute="IndexAttrName"
							/>
					</AttributePairs>
				</Alias>
			</Aliases>
		</RelToChildDO>
		<RelToChildDO
			RelToChildDO="ValidationAttr(Attribute)-Validations(Validation)"
		>
			<Aliases>
				<Alias
					Name="Attribute"
				>
					<AttributePairs>
				<AttributePair
							ParentAttribute="RepositoryName"
							ChildAttribute="RepositoryName"
							/>
				<AttributePair
							ParentAttribute="DataObjectName"
							ChildAttribute="DataObjectName"
							/>
				<AttributePair
							ParentAttribute="AttrName"
							ChildAttribute="AttrName"
							/>
					</AttributePairs>
				</Alias>
			</Aliases>
		</RelToChildDO>
		<RelToChildDO
			RelToChildDO="Attribute2(Attribute)-Validation(Validation)"
		>
			<Aliases>
				<Alias
					Name="Attribute"
				>
					<AttributePairs>
				<AttributePair
							ParentAttribute="RepositoryName"
							ChildAttribute="RepositoryName"
							/>
				<AttributePair
							ParentAttribute="DataObjectName"
							ChildAttribute="CodedValueList"
							/>
				<AttributePair
							ParentAttribute="AttrName"
							ChildAttribute="AttrName"
							/>
					</AttributePairs>
				</Alias>
			</Aliases>
		</RelToChildDO>
		<RelToChildDO
			RelToChildDO="SourceAttribute(Attribute)-AttrObjectMapper(AttrObjectMapper)"
		>
			<Aliases>
				<Alias
					Name="Attribute"
				>
					<AttributePairs>
				<AttributePair
							ParentAttribute="RepositoryName"
							ChildAttribute="SourceRepositoryName"
							/>
				<AttributePair
							ParentAttribute="DataObjectName"
							ChildAttribute="SourceDataObjectName"
							/>
				<AttributePair
							ParentAttribute="AttrName"
							ChildAttribute="SourceAttrName"
							/>
					</AttributePairs>
				</Alias>
			</Aliases>
		</RelToChildDO>
		<RelToChildDO
			RelToChildDO="TargetAttribute(Attribute)-AttrObjectMapper_1(AttrObjectMapper)"
		>
			<Aliases>
				<Alias
					Name="Attribute"
				>
					<AttributePairs>
				<AttributePair
							ParentAttribute="RepositoryName"
							ChildAttribute="TargetRepositoryName"
							/>
				<AttributePair
							ParentAttribute="DataObjectName"
							ChildAttribute="TargetDataObjectName"
							/>
				<AttributePair
							ParentAttribute="AttrName"
							ChildAttribute="TargetAttrName"
							/>
					</AttributePairs>
				</Alias>
			</Aliases>
		</RelToChildDO>
	</RelsToChildDataObjects>

	<PickSupportedRels>
		<PickSupportedRel
			PickSupportedRel="DerivationAttr(Attribute)-Derivations(Derivation)"
		/>
		<PickSupportedRel
			PickSupportedRel="Attribute(Attribute)-Derivation(Derivation)"
		/>
		<PickSupportedRel
			PickSupportedRel="Attribute1(Attribute)-IndexAttr(IndexAttr)"
		/>
		<PickSupportedRel
			PickSupportedRel="ValidationAttr(Attribute)-Validations(Validation)"
		/>
		<PickSupportedRel
			PickSupportedRel="Attribute2(Attribute)-Validation(Validation)"
		/>
		<PickSupportedRel
			PickSupportedRel="SourceAttribute(Attribute)-AttrObjectMapper(AttrObjectMapper)"
		/>
		<PickSupportedRel
			PickSupportedRel="TargetAttribute(Attribute)-AttrObjectMapper_1(AttrObjectMapper)"
		/>
	</PickSupportedRels >

</QueryObject>
