=== tylerm007/MetaRepos/Source/ClientApps/JavaApps/ObjectDiff.app/Form.dtd
<!ELEMENT Form ( FormCaption | Description | ArchetypeExtendedProperties | ExtendedProperties | FormLayout | RecordSource | Transition  )* >
<!ATTLIST Form 
	TargetLanguage CDATA #REQUIRED 
	Archetype CDATA #IMPLIED 
	PositionTop CDATA   #IMPLIED
	PositionLeft CDATA   #IMPLIED
	PositionWidth CDATA  #IMPLIED
	PositionHeight CDATA   #IMPLIED
	IsAddedAfterGen (True|False) #IMPLIED
	DirtyFlag (b|d|i|BLANK)  #IMPLIED 
	HasCustomFormLayout (True|False)  #IMPLIED
	ObjectsUnusedByFormLayout (True|False) #IMPLIED
	ClassName CDATA #IMPLIED
	ObjectsRemovedFromLayout  (True|False) #IMPLIED
	External (True|False) #IMPLIED
	NoDataForm (True|False) #IMPLIED
	DTDVersion CDATA #REQUIRED
	HTMLFileCheckSum CDATA #IMPLIED
>

<!ELEMENT FormCaption (#PCDATA) >
<!ELEMENT Description (#PCDATA) >
<!ELEMENT ArchetypeExtendedProperties (Property)* >
<!ELEMENT ExtendedProperties (Property)* >
<!ELEMENT FormLayout (#PCDATA) >

<!ELEMENT Property EMPTY>
<!ATTLIST Property 
	Name CDATA #REQUIRED
	Value CDATA #REQUIRED
>

<!ELEMENT RecordSource (OrderByClause | ParameterizedWhereClause | AdditionalWhereClause | ArchetypeExtendedProperties | ExtendedProperties | Description | RSAttributesMeta | RecordSource | PickObject | Transition )* >
<!ATTLIST RecordSource 
	RSID CDATA #REQUIRED
	Prefix CDATA #REQUIRED
	BusinessObject CDATA #REQUIRED
	RecordSourceArchetype CDATA #REQUIRED
	Relationship CDATA #IMPLIED
	RelnIsFromParent (True|False) #IMPLIED
	DoesSourceAffectMe (True|False) #IMPLIED
	DoIAffectSource (True|False) #IMPLIED
	IsAddedAfterGen (True|False) #IMPLIED
	RsAttributesDefault (True|False) #IMPLIED
	ClassName   CDATA  #IMPLIED
	MaxGridRowCount CDATA  #IMPLIED   
	FetchedBlockRowCount CDATA  #IMPLIED
	AllowDelete  (True|False) #IMPLIED
	AllowInsert  (True|False) #IMPLIED
	AllowUpdate  (True|False) #IMPLIED
	SaveMode (Buffered|Immediate) #IMPLIED
	PreFetchRowCount  (True|False) #IMPLIED
	ParentAlias  CDATA  #IMPLIED
	ChildAlias   CDATA  #IMPLIED
>

<!ELEMENT OrderByClause  (#PCDATA)>
<!ELEMENT ParameterizedWhereClause  (#PCDATA)>
<!ELEMENT AdditionalWhereClause  (#PCDATA)>
<!ELEMENT RSAttributesMeta  ( DefaultAttributes | ScalerAttributes | GridAttributes )* >
<!ELEMENT DefaultAttributes (RSDefaultAttribute)* >
<!ELEMENT ScalerAttributes (RSAttribute)* >
<!ELEMENT GridAttributes (RSAttribute)* >
<!ELEMENT RSDefaultAttribute EMPTY >
<!ATTLIST RSDefaultAttribute
	ID CDATA #REQUIRED
	Name CDATA #REQUIRED
>
<!ELEMENT RSAttribute EMPTY >
<!ATTLIST RSAttribute
	Name CDATA #REQUIRED
	Displayed CDATA #IMPLIED
	UnPlaced CDATA #IMPLIED
	Archetype CDATA #IMPLIED
	TransitionToUse CDATA #IMPLIED
>

<!ELEMENT Transition (OrderByClause | ParameterizedWhereClause | AdditionalWhereClause | ExtendedProperties | Description)* >
<!ATTLIST Transition
	FormTransNum  CDATA #IMPLIED
	BusinessObject CDATA #IMPLIED
	RSID CDATA #IMPLIED
	Prefix CDATA #REQUIRED
	TargetFormName CDATA #REQUIRED
	IsTargetInitialQueryMode  (True|False) #IMPLIED
	IsTargetInitialAddMode (True|False) #IMPLIED
	IsVisibleAppline (True|False) #IMPLIED
	Relationship CDATA #IMPLIED
	RelnIsFromParent CDATA #IMPLIED
	IsAddedAfterGen (True|False) #IMPLIED
	FormTransCaption CDATA  #IMPLIED
	ClassName CDATA #IMPLIED
	TargetFramesetPage CDATA #IMPLIED  
	TargetFrame CDATA #IMPLIED   
	FrameNameInFramesetPage CDATA #IMPLIED
>

<!ELEMENT PickObject (OrderByClause | FKeyParamsClause | AdditionalWhereClause | ExtendedProperties | Description | RSAttributesMeta )* >
<!ATTLIST PickObject 
	RSID CDATA #REQUIRED
	Prefix CDATA #REQUIRED
	BusinessObject CDATA #REQUIRED
	Relationship CDATA #IMPLIED
	RelnIsFromParent (True|False) #IMPLIED
	OrderByClause CDATA   #IMPLIED
	PickTargetFormName CDATA #IMPLIED
	DoesSourceAffectMe CDATA   #IMPLIED
	DoIAffectSource CDATA   #IMPLIED
	IsAddedAfterGen (True|False) #IMPLIED
	RsAttributesDefault (True|False) #IMPLIED
	OnScreenPick (True|False) #IMPLIED
	ClassName  CDATA   #IMPLIED
>
<!ELEMENT FKeyParamsClause  (#PCDATA)>

=== tylerm007/MetaRepos/Source/ClientApps/HTMLApps/HTML_ReposMaint.app/pAttribute_Grid.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Form SYSTEM "Form.dtd">
<Form
	DTDVersion="05.05.12"
	TargetLanguage="HTML"
	Archetype="Default"
	PositionTop="456.25"
	PositionLeft="590.625"
	PositionWidth="187.5"
	PositionHeight="54.6875"
	IsAddedAfterGen="False"
	HasCustomFormLayout="False"
	ObjectsUnusedByFormLayout="False"
	External="False"
	NoDataForm="False"
	ClassName="versata.pdx.html.VSPagePDX"
	ObjectsRemovedFromLayout="False"
	HTMLFileCheckSum="545991578"
	>
	<FormCaption><![CDATA[Attribute(s)]]></FormCaption>
	<ArchetypeExtendedProperties>
		<Property
			Name="Comments"
			Value=""
		/>
		<Property
			Name="CommentsTrailing"
			Value=""
		/>
		<Property
			Name="CrumbTrailEnabled"
			Value="true"
		/>
		<Property
			Name="CrumbTrailIncludesThisPage"
			Value="true"
		/>
		<Property
			Name="CrumbTrailRestartsHere"
			Value="false"
		/>
		<Property
			Name="CrumbTrailSeparator"
			Value="&gt;"
		/>
		<Property
			Name="ErrorStyle"
			Value="Popup"
		/>
		<Property
			Name="IncludeFooter"
			Value="false"
		/>
		<Property
			Name="IncludeHeader"
			Value="false"
		/>
		<Property
			Name="IncludeLeftBar"
			Value="false"
		/>
		<Property
			Name="IncludeRightBar"
			Value="false"
		/>
		<Property
			Name="ShowCancelButton"
			Value="true"
		/>
		<Property
			Name="ShowFormCaption"
			Value="true"
		/>
		<Property
			Name="ShowReturnButton"
			Value="true"
		/>
		<Property
			Name="TransitionsToHide"
			Value=""
		/>
	</ArchetypeExtendedProperties>
	<RecordSource
		RSID="1"
		Prefix="T1"
		BusinessObject="Attribute"
		RelnIsFromParent="False"
		DoesSourceAffectMe="False"
		DoIAffectSource="False"
		IsAddedAfterGen="False"
		RsAttributesDefault="True"
		ClassName="versata.pdx.html.DataSourcePDX"
		RecordSourceArchetype="GridUpdatable"
		MaxGridRowCount="10"
		FetchedBlockRowCount="16"
		AllowDelete="True"
		AllowInsert="True"
		AllowUpdate="True"
		SaveMode="Immediate"
		PreFetchRowCount="False"
		>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<RSAttributesMeta>
			<DefaultAttributes>
				<RSDefaultAttribute ID="1" Name="RepositoryName" />
				<RSDefaultAttribute ID="2" Name="DataObjectName" />
				<RSDefaultAttribute ID="3" Name="AttrName" />
				<RSDefaultAttribute ID="4" Name="Persistent" />
				<RSDefaultAttribute ID="5" Name="PreventUserUpdate" />
				<RSDefaultAttribute ID="6" Name="ValueRequired" />
				<RSDefaultAttribute ID="7" Name="DataType" />
				<RSDefaultAttribute ID="8" Name="AttrSize" />
				<RSDefaultAttribute ID="9" Name="Description" />
				<RSDefaultAttribute ID="10" Name="Caption" />
				<RSDefaultAttribute ID="11" Name="Comments" />
				<RSDefaultAttribute ID="12" Name="Format" />
				<RSDefaultAttribute ID="13" Name="MicroHelp" />
				<RSDefaultAttribute ID="14" Name="Derivation_Cnt" />
				<RSDefaultAttribute ID="15" Name="Validation_Cnt" />
				<RSDefaultAttribute ID="16" Name="Formula_Cnt" />
				<RSDefaultAttribute ID="17" Name="Sum_Cnt" />
				<RSDefaultAttribute ID="18" Name="Count_Cnt" />
				<RSDefaultAttribute ID="19" Name="ParentRepl_Cnt" />
				<RSDefaultAttribute ID="20" Name="Precision" />
				<RSDefaultAttribute ID="21" Name="Scale" />
				<RSDefaultAttribute ID="22" Name="SQLDataType" />
			</DefaultAttributes>
			<GridAttributes>
				<RSAttribute Name="RepositoryName" Displayed="False" UnPlaced="False" />
				<RSAttribute Name="DataObjectName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="AttrName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Persistent" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="PreventUserUpdate" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ValueRequired" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="DataType" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="AttrSize" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Description" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Caption" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Comments" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Format" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="MicroHelp" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Derivation_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Validation_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Formula_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Sum_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Count_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ParentRepl_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Precision" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Scale" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="SQLDataType" Displayed="True" UnPlaced="False" />
			</GridAttributes>
		</RSAttributesMeta>
		<ExtendedProperties>
			<Property
				Name="ColumnProjectionLevel"
				Value=""
			/>
			<Property
				Name="PreFetchRowCount"
				Value=""
			/>
			<Property
				Name="VirtualResultSet"
				Value=""
			/>
			<Property
				Name="ZoomDataSource"
				Value=""
			/>
		</ExtendedProperties>
		<ArchetypeExtendedProperties>
			<Property
				Name="AltRowColor"
				Value="#EFEFEF"
			/>
			<Property
				Name="Caption"
				Value=""
			/>
			<Property
				Name="Comments"
				Value=""
			/>
			<Property
				Name="CommentsTrailing"
				Value="&lt;br&gt;"
			/>
			<Property
				Name="Cond0HideRecSrc"
				Value=""
			/>
			<Property
				Name="Cond1"
				Value=""
			/>
			<Property
				Name="Cond1Actions"
				Value=""
			/>
			<Property
				Name="Cond2"
				Value=""
			/>
			<Property
				Name="Cond2Actions"
				Value=""
			/>
			<Property
				Name="Cond3"
				Value=""
			/>
			<Property
				Name="Cond3Actions"
				Value=""
			/>
			<Property
				Name="Cond4"
				Value=""
			/>
			<Property
				Name="Cond4Actions"
				Value=""
			/>
			<Property
				Name="Cond5"
				Value=""
			/>
			<Property
				Name="Cond5Actions"
				Value=""
			/>
			<Property
				Name="ConfirmDeleteMsg"
				Value="Delete record?"
			/>
			<Property
				Name="NoDataMessage"
				Value="&lt;br&gt;&lt;center&gt;&lt;b&gt;No records found!&lt;/b&gt;&lt;/center&gt;&lt;br&gt;"
			/>
			<Property
				Name="ShowHeader"
				Value="true"
			/>
			<Property
				Name="ShowRowCount"
				Value="true"
			/>
			<Property
				Name="ShowRowSelector"
				Value="true"
			/>
			<Property
				Name="SortableHeader"
				Value="true"
			/>
			<Property
				Name="TabCaption"
				Value=""
			/>
			<Property
				Name="TabGenerated"
				Value="true"
			/>
			<Property
				Name="TabImageHeight"
				Value=""
			/>
			<Property
				Name="TabImageOff"
				Value=""
			/>
			<Property
				Name="TabImageOn"
				Value=""
			/>
			<Property
				Name="TabImageWidth"
				Value=""
			/>
			<Property
				Name="UsePopupPicks"
				Value="true"
			/>
		</ArchetypeExtendedProperties>
		<Transition
			FormTransNum="1"
			Prefix="T2"
			TargetFormName="pAttribute"
			IsTargetInitialQueryMode="False"
			IsTargetInitialAddMode="False"
			IsVisibleAppline="True"
			IsAddedAfterGen="False"
			ClassName="PageNavigation"
			TargetFramesetPage=""
			TargetFrame=""
			FrameNameInFramesetPage=""
			>
		</Transition>
	</RecordSource>
</Form>

=== tylerm007/MetaRepos/Source/ClientApps/HTMLApps/HTML_ReposMaint.app/pMethod_Grid.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Form SYSTEM "Form.dtd">
<Form
	DTDVersion="05.05.12"
	TargetLanguage="HTML"
	Archetype="Default"
	PositionTop="626.25"
	PositionLeft="596.25"
	PositionWidth="187.5"
	PositionHeight="55"
	IsAddedAfterGen="False"
	HasCustomFormLayout="False"
	ObjectsUnusedByFormLayout="False"
	External="False"
	NoDataForm="False"
	ClassName="versata.pdx.html.VSPagePDX"
	ObjectsRemovedFromLayout="False"
	HTMLFileCheckSum="-768176220"
	>
	<FormCaption><![CDATA[User Methods]]></FormCaption>
	<ArchetypeExtendedProperties>
		<Property
			Name="Comments"
			Value=""
		/>
		<Property
			Name="CommentsTrailing"
			Value=""
		/>
		<Property
			Name="CrumbTrailEnabled"
			Value="true"
		/>
		<Property
			Name="CrumbTrailIncludesThisPage"
			Value="true"
		/>
		<Property
			Name="CrumbTrailRestartsHere"
			Value="false"
		/>
		<Property
			Name="CrumbTrailSeparator"
			Value="&gt;"
		/>
		<Property
			Name="ErrorStyle"
			Value="Popup"
		/>
		<Property
			Name="IncludeFooter"
			Value="false"
		/>
		<Property
			Name="IncludeHeader"
			Value="false"
		/>
		<Property
			Name="IncludeLeftBar"
			Value="false"
		/>
		<Property
			Name="IncludeRightBar"
			Value="false"
		/>
		<Property
			Name="ShowCancelButton"
			Value="true"
		/>
		<Property
			Name="ShowFormCaption"
			Value="true"
		/>
		<Property
			Name="ShowReturnButton"
			Value="true"
		/>
		<Property
			Name="TransitionsToHide"
			Value=""
		/>
	</ArchetypeExtendedProperties>
	<RecordSource
		RSID="1"
		Prefix="T1"
		BusinessObject="Method"
		RelnIsFromParent="False"
		DoesSourceAffectMe="False"
		DoIAffectSource="False"
		IsAddedAfterGen="False"
		RsAttributesDefault="True"
		ClassName="versata.pdx.html.DataSourcePDX"
		RecordSourceArchetype="Grid"
		MaxGridRowCount="10"
		FetchedBlockRowCount="16"
		AllowDelete="False"
		AllowInsert="False"
		AllowUpdate="False"
		SaveMode="Immediate"
		PreFetchRowCount="False"
		>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<RSAttributesMeta>
			<DefaultAttributes>
				<RSDefaultAttribute ID="1" Name="RepositoryName" />
				<RSDefaultAttribute ID="2" Name="MethodName" />
				<RSDefaultAttribute ID="3" Name="ReturnType" />
				<RSDefaultAttribute ID="4" Name="Signature" />
				<RSDefaultAttribute ID="5" Name="ObjectName" />
				<RSDefaultAttribute ID="6" Name="ObjectType" />
				<RSDefaultAttribute ID="7" Name="MethodSource" />
				<RSDefaultAttribute ID="8" Name="IsPublic" />
				<RSDefaultAttribute ID="9" Name="IsUserDefined" />
			</DefaultAttributes>
			<GridAttributes>
				<RSAttribute Name="RepositoryName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="MethodName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ReturnType" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Signature" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ObjectName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ObjectType" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="MethodSource" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="IsPublic" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="IsUserDefined" Displayed="True" UnPlaced="False" />
			</GridAttributes>
		</RSAttributesMeta>
		<ArchetypeExtendedProperties>
			<Property
				Name="AltRowColor"
				Value="#EFEFEF"
			/>
			<Property
				Name="Caption"
				Value=""
			/>
			<Property
				Name="Comments"
				Value=""
			/>
			<Property
				Name="CommentsTrailing"
				Value="&lt;br&gt;"
			/>
			<Property
				Name="Cond0HideRecSrc"
				Value=""
			/>
			<Property
				Name="Cond1"
				Value=""
			/>
			<Property
				Name="Cond1Actions"
				Value=""
			/>
			<Property
				Name="Cond2"
				Value=""
			/>
			<Property
				Name="Cond2Actions"
				Value=""
			/>
			<Property
				Name="Cond3"
				Value=""
			/>
			<Property
				Name="Cond3Actions"
				Value=""
			/>
			<Property
				Name="Cond4"
				Value=""
			/>
			<Property
				Name="Cond4Actions"
				Value=""
			/>
			<Property
				Name="Cond5"
				Value=""
			/>
			<Property
				Name="Cond5Actions"
				Value=""
			/>
			<Property
				Name="ConfirmDeleteMsg"
				Value="Delete record?"
			/>
			<Property
				Name="NoDataMessage"
				Value="&lt;br&gt;&lt;center&gt;&lt;b&gt;No records found!&lt;/b&gt;&lt;/center&gt;&lt;br&gt;"
			/>
			<Property
				Name="ShowHeader"
				Value="true"
			/>
			<Property
				Name="ShowRowCount"
				Value="true"
			/>
			<Property
				Name="ShowRowSelector"
				Value="true"
			/>
			<Property
				Name="SortableHeader"
				Value="true"
			/>
			<Property
				Name="TabCaption"
				Value=""
			/>
			<Property
				Name="TabGenerated"
				Value="true"
			/>
			<Property
				Name="TabImageHeight"
				Value=""
			/>
			<Property
				Name="TabImageOff"
				Value=""
			/>
			<Property
				Name="TabImageOn"
				Value=""
			/>
			<Property
				Name="TabImageWidth"
				Value=""
			/>
			<Property
				Name="UsePopupPicks"
				Value="true"
			/>
		</ArchetypeExtendedProperties>
	</RecordSource>
</Form>

=== tylerm007/MetaRepos/Source/ClientApps/HTMLApps/Project1.app/StartupPage.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Form SYSTEM "Form.dtd">
<Form
	DTDVersion="05.05.12"
	TargetLanguage="HTML"
	Archetype="Startup"
	PositionTop="5"
	PositionLeft="12.5"
	PositionWidth="150"
	PositionHeight="43.75"
	IsAddedAfterGen="False"
	HasCustomFormLayout="False"
	ObjectsUnusedByFormLayout="False"
	External="False"
	NoDataForm="False"
	ClassName="versata.pdx.html.VSPagePDX"
	ObjectsRemovedFromLayout="False"
	HTMLFileCheckSum="854827790"
	>
	<FormCaption><![CDATA[StartupPage]]></FormCaption>
	<ArchetypeExtendedProperties>
		<Property
			Name="LogoImage"
			Value="images/logo.gif"
		/>
		<Property
			Name="MenuTabsEnabled"
			Value="true"
		/>
		<Property
			Name="TransitionsToHide"
			Value=""
		/>
	</ArchetypeExtendedProperties>
	<ExtendedProperties>
		<Property
			Name="ContainerPageElement"
			Value=""
		/>
		<Property
			Name="Title"
			Value=""
		/>
	</ExtendedProperties>
	<Transition
		FormTransNum="1"
		Prefix="T2"
		TargetFormName="pReposVersion"
		IsTargetInitialQueryMode="False"
		IsTargetInitialAddMode="False"
		IsVisibleAppline="True"
		IsAddedAfterGen="False"
		FormTransCaption=" "
		ClassName="PageNavigation"
		TargetFramesetPage=""
		TargetFrame="Display"
		FrameNameInFramesetPage=""
		RSID="2"
		BusinessObject="ReposVersion"
		RelnIsFromParent="True"
		>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
	</Transition>
	<Transition
		FormTransNum="1"
		Prefix="T1"
		TargetFormName="pDataObject"
		IsTargetInitialQueryMode="True"
		IsTargetInitialAddMode="False"
		IsVisibleAppline="True"
		IsAddedAfterGen="False"
		FormTransCaption=" "
		ClassName="PageNavigation"
		TargetFramesetPage=""
		TargetFrame="Display"
		FrameNameInFramesetPage=""
		RSID="3"
		BusinessObject="DataObject"
		RelnIsFromParent="True"
		>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
	</Transition>
	<Transition
		FormTransNum="1"
		Prefix="T3"
		TargetFormName="pAttribute"
		IsTargetInitialQueryMode="True"
		IsTargetInitialAddMode="False"
		IsVisibleAppline="True"
		IsAddedAfterGen="False"
		FormTransCaption=" "
		ClassName="PageNavigation"
		TargetFramesetPage=""
		TargetFrame="Display"
		FrameNameInFramesetPage=""
		RSID="4"
		BusinessObject="Attribute"
		RelnIsFromParent="True"
		>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
	</Transition>
	<Transition
		FormTransNum="1"
		Prefix="T4"
		TargetFormName="pRelationship"
		IsTargetInitialQueryMode="False"
		IsTargetInitialAddMode="False"
		IsVisibleAppline="True"
		IsAddedAfterGen="False"
		ClassName="PageNavigation"
		TargetFramesetPage=""
		TargetFrame="Display"
		FrameNameInFramesetPage=""
		RSID="5"
		BusinessObject="Relationship"
		RelnIsFromParent="True"
		>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
	</Transition>
	<Transition
		FormTransNum="1"
		Prefix="T5"
		TargetFormName="pApplication"
		IsTargetInitialQueryMode="True"
		IsTargetInitialAddMode="False"
		IsVisibleAppline="True"
		IsAddedAfterGen="False"
		FormTransCaption="Application"
		ClassName="PageNavigation"
		TargetFramesetPage=""
		TargetFrame="Display"
		FrameNameInFramesetPage=""
		RSID="6"
		BusinessObject="Application"
		RelnIsFromParent="True"
		>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
	</Transition>
	<Transition
		FormTransNum="1"
		Prefix="T6"
		TargetFormName="pQueryObject_Grid"
		IsTargetInitialQueryMode="True"
		IsTargetInitialAddMode="False"
		IsVisibleAppline="True"
		IsAddedAfterGen="False"
		FormTransCaption=" "
		ClassName="PageNavigation"
		TargetFramesetPage=""
		TargetFrame="Display"
		FrameNameInFramesetPage=""
		RSID="7"
		BusinessObject="QueryObject"
		RelnIsFromParent="True"
		>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
	</Transition>
</Form>

=== tylerm007/MetaRepos/Source/ClientApps/HTMLApps/Project1.app/pQry_AttrParentRepl_Grid.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Form SYSTEM "Form.dtd">
<Form
	DTDVersion="05.05.12"
	TargetLanguage="HTML"
	Archetype="Default"
	PositionTop="458"
	PositionLeft="214"
	PositionWidth="215"
	PositionHeight="44"
	IsAddedAfterGen="False"
	HasCustomFormLayout="False"
	ObjectsUnusedByFormLayout="False"
	External="False"
	NoDataForm="False"
	ClassName="versata.pdx.html.VSPagePDX"
	ObjectsRemovedFromLayout="False"
	HTMLFileCheckSum="-231917153"
	>
	<FormCaption><![CDATA[Parent Repl Attrs]]></FormCaption>
	<ArchetypeExtendedProperties>
		<Property
			Name="Comments"
			Value=""
		/>
		<Property
			Name="CommentsTrailing"
			Value=""
		/>
		<Property
			Name="CrumbTrailEnabled"
			Value="true"
		/>
		<Property
			Name="CrumbTrailIncludesThisPage"
			Value="true"
		/>
		<Property
			Name="CrumbTrailRestartsHere"
			Value="false"
		/>
		<Property
			Name="CrumbTrailSeparator"
			Value="&gt;"
		/>
		<Property
			Name="ErrorStyle"
			Value="Popup"
		/>
		<Property
			Name="IncludeFooter"
			Value="false"
		/>
		<Property
			Name="IncludeHeader"
			Value="false"
		/>
		<Property
			Name="IncludeLeftBar"
			Value="false"
		/>
		<Property
			Name="IncludeRightBar"
			Value="false"
		/>
		<Property
			Name="ShowCancelButton"
			Value="true"
		/>
		<Property
			Name="showFormCaption"
			Value="true"
		/>
		<Property
			Name="ShowReturnButton"
			Value="true"
		/>
		<Property
			Name="TransitionsToHide"
			Value=""
		/>
	</ArchetypeExtendedProperties>
	<RecordSource
		RSID="1"
		Prefix="T1"
		BusinessObject="Qry_AttrParentRepl"
		RelnIsFromParent="False"
		DoesSourceAffectMe="False"
		DoIAffectSource="False"
		IsAddedAfterGen="False"
		RsAttributesDefault="False"
		ClassName="versata.pdx.html.DataSourcePDX"
		RecordSourceArchetype="Grid"
		MaxGridRowCount="10"
		FetchedBlockRowCount="16"
		AllowDelete="False"
		AllowInsert="False"
		AllowUpdate="False"
		SaveMode="Immediate"
		PreFetchRowCount="False"
		>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<RSAttributesMeta>
			<DefaultAttributes>
				<RSDefaultAttribute ID="1" Name="AttrName" />
				<RSDefaultAttribute ID="2" Name="Persistent" />
				<RSDefaultAttribute ID="3" Name="ValueRequired" />
				<RSDefaultAttribute ID="4" Name="PreventUserUpdate" />
				<RSDefaultAttribute ID="5" Name="DataType" />
				<RSDefaultAttribute ID="6" Name="Size" />
				<RSDefaultAttribute ID="7" Name="Caption" />
				<RSDefaultAttribute ID="8" Name="Description" />
				<RSDefaultAttribute ID="9" Name="Comments" />
				<RSDefaultAttribute ID="10" Name="SourceAttr" />
				<RSDefaultAttribute ID="11" Name="SourceDataObject" />
				<RSDefaultAttribute ID="12" Name="ParentReplicateIsMaintained" />
				<RSDefaultAttribute ID="13" Name="ParentRepl_Cnt" />
				<RSDefaultAttribute ID="14" Name="RepositoryName" />
				<RSDefaultAttribute ID="15" Name="DataObjectName" />
			</DefaultAttributes>
			<ScalerAttributes>
				<RSAttribute Name="AttrName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Persistent" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ValueRequired" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="PreventUserUpdate" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="DataType" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Size" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Caption" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Description" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Comments" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="SourceAttr" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="SourceDataObject" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ParentReplicateIsMaintained" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ParentRepl_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="RepositoryName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="DataObjectName" Displayed="True" UnPlaced="False" />
			</ScalerAttributes>
			<GridAttributes>
				<RSAttribute Name="AttrName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Persistent" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ValueRequired" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="PreventUserUpdate" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="DataType" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Size" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Caption" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Description" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Comments" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="SourceAttr" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="SourceDataObject" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ParentReplicateIsMaintained" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ParentRepl_Cnt" Displayed="False" UnPlaced="False" />
				<RSAttribute Name="RepositoryName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="DataObjectName" Displayed="True" UnPlaced="False" />
			</GridAttributes>
		</RSAttributesMeta>
		<ArchetypeExtendedProperties>
			<Property
				Name="AltRowColor"
				Value="#DFE5EF"
			/>
			<Property
				Name="Caption"
				Value=""
			/>
			<Property
				Name="Comments"
				Value=""
			/>
			<Property
				Name="CommentsTrailing"
				Value="&lt;br&gt;"
			/>
			<Property
				Name="Cond0HideRecSrc"
				Value=""
			/>
			<Property
				Name="Cond1"
				Value=""
			/>
			<Property
				Name="Cond1Actions"
				Value=""
			/>
			<Property
				Name="Cond2"
				Value=""
			/>
			<Property
				Name="Cond2Actions"
				Value=""
			/>
			<Property
				Name="Cond3"
				Value=""
			/>
			<Property
				Name="Cond3Actions"
				Value=""
			/>
			<Property
				Name="Cond4"
				Value=""
			/>
			<Property
				Name="Cond4Actions"
				Value=""
			/>
			<Property
				Name="Cond5"
				Value=""
			/>
			<Property
				Name="Cond5Actions"
				Value=""
			/>
			<Property
				Name="ConfirmDeleteMsg"
				Value="Delete record?"
			/>
			<Property
				Name="NoDataMessage"
				Value="&lt;br&gt;&lt;center&gt;&lt;b&gt;No records found!&lt;/b&gt;&lt;/center&gt;&lt;br&gt;"
			/>
			<Property
				Name="ShowHeader"
				Value="true"
			/>
			<Property
				Name="ShowRowCount"
				Value="true"
			/>
			<Property
				Name="ShowRowSelector"
				Value="true"
			/>
			<Property
				Name="SortableHeader"
				Value="true"
			/>
			<Property
				Name="TabCaption"
				Value=""
			/>
			<Property
				Name="TabGenerated"
				Value="true"
			/>
			<Property
				Name="TabImageHeight"
				Value=""
			/>
			<Property
				Name="TabImageOff"
				Value=""
			/>
			<Property
				Name="TabImageOn"
				Value=""
			/>
			<Property
				Name="TabImageWidth"
				Value=""
			/>
			<Property
				Name="UsePopupPicks"
				Value="true"
			/>
		</ArchetypeExtendedProperties>
	</RecordSource>
</Form>
