=== tylerm007/MetaRepos/Source/ClientApps/JavaApps/ObjectDiff.app/Form.dtd
<!ELEMENT Form ( FormCaption | Description | ArchetypeExtendedProperties | ExtendedProperties | FormLayout | RecordSource | Transition  )* >
<!ATTLIST Form 
	TargetLanguage CDATA #REQUIRED 
	Archetype CDATA #IMPLIED 
	PositionTop CDATA   #IMPLIED
	PositionLeft CDATA   #IMPLIED
	PositionWidth CDATA  #IMPLIED
	PositionHeight CDATA   #IMPLIED
	IsAddedAfterGen (True|False) #IMPLIED
	DirtyFlag (b|d|i|BLANK)  #IMPLIED 
	HasCustomFormLayout (True|False)  #IMPLIED
	ObjectsUnusedByFormLayout (True|False) #IMPLIED
	ClassName CDATA #IMPLIED
	ObjectsRemovedFromLayout  (True|False) #IMPLIED
	External (True|False) #IMPLIED
	NoDataForm (True|False) #IMPLIED
	DTDVersion CDATA #REQUIRED
	HTMLFileCheckSum CDATA #IMPLIED
>

<!ELEMENT FormCaption (#PCDATA) >
<!ELEMENT Description (#PCDATA) >
<!ELEMENT ArchetypeExtendedProperties (Property)* >
<!ELEMENT ExtendedProperties (Property)* >
<!ELEMENT FormLayout (#PCDATA) >

<!ELEMENT Property EMPTY>
<!ATTLIST Property 
	Name CDATA #REQUIRED
	Value CDATA #REQUIRED
>

<!ELEMENT RecordSource (OrderByClause | ParameterizedWhereClause | AdditionalWhereClause | ArchetypeExtendedProperties | ExtendedProperties | Description | RSAttributesMeta | RecordSource | PickObject | Transition )* >
<!ATTLIST RecordSource 
	RSID CDATA #REQUIRED
	Prefix CDATA #REQUIRED
	BusinessObject CDATA #REQUIRED
	RecordSourceArchetype CDATA #REQUIRED
	Relationship CDATA #IMPLIED
	RelnIsFromParent (True|False) #IMPLIED
	DoesSourceAffectMe (True|False) #IMPLIED
	DoIAffectSource (True|False) #IMPLIED
	IsAddedAfterGen (True|False) #IMPLIED
	RsAttributesDefault (True|False) #IMPLIED
	ClassName   CDATA  #IMPLIED
	MaxGridRowCount CDATA  #IMPLIED   
	FetchedBlockRowCount CDATA  #IMPLIED
	AllowDelete  (True|False) #IMPLIED
	AllowInsert  (True|False) #IMPLIED
	AllowUpdate  (True|False) #IMPLIED
	SaveMode (Buffered|Immediate) #IMPLIED
	PreFetchRowCount  (True|False) #IMPLIED
	ParentAlias  CDATA  #IMPLIED
	ChildAlias   CDATA  #IMPLIED
>

<!ELEMENT OrderByClause  (#PCDATA)>
<!ELEMENT ParameterizedWhereClause  (#PCDATA)>
<!ELEMENT AdditionalWhereClause  (#PCDATA)>
<!ELEMENT RSAttributesMeta  ( DefaultAttributes | ScalerAttributes | GridAttributes )* >
<!ELEMENT DefaultAttributes (RSDefaultAttribute)* >
<!ELEMENT ScalerAttributes (RSAttribute)* >
<!ELEMENT GridAttributes (RSAttribute)* >
<!ELEMENT RSDefaultAttribute EMPTY >
<!ATTLIST RSDefaultAttribute
	ID CDATA #REQUIRED
	Name CDATA #REQUIRED
>
<!ELEMENT RSAttribute EMPTY >
<!ATTLIST RSAttribute
	Name CDATA #REQUIRED
	Displayed CDATA #IMPLIED
	UnPlaced CDATA #IMPLIED
	Archetype CDATA #IMPLIED
	TransitionToUse CDATA #IMPLIED
>

<!ELEMENT Transition (OrderByClause | ParameterizedWhereClause | AdditionalWhereClause | ExtendedProperties | Description)* >
<!ATTLIST Transition
	FormTransNum  CDATA #IMPLIED
	BusinessObject CDATA #IMPLIED
	RSID CDATA #IMPLIED
	Prefix CDATA #REQUIRED
	TargetFormName CDATA #REQUIRED
	IsTargetInitialQueryMode  (True|False) #IMPLIED
	IsTargetInitialAddMode (True|False) #IMPLIED
	IsVisibleAppline (True|False) #IMPLIED
	Relationship CDATA #IMPLIED
	RelnIsFromParent CDATA #IMPLIED
	IsAddedAfterGen (True|False) #IMPLIED
	FormTransCaption CDATA  #IMPLIED
	ClassName CDATA #IMPLIED
	TargetFramesetPage CDATA #IMPLIED  
	TargetFrame CDATA #IMPLIED   
	FrameNameInFramesetPage CDATA #IMPLIED
>

<!ELEMENT PickObject (OrderByClause | FKeyParamsClause | AdditionalWhereClause | ExtendedProperties | Description | RSAttributesMeta )* >
<!ATTLIST PickObject 
	RSID CDATA #REQUIRED
	Prefix CDATA #REQUIRED
	BusinessObject CDATA #REQUIRED
	Relationship CDATA #IMPLIED
	RelnIsFromParent (True|False) #IMPLIED
	OrderByClause CDATA   #IMPLIED
	PickTargetFormName CDATA #IMPLIED
	DoesSourceAffectMe CDATA   #IMPLIED
	DoIAffectSource CDATA   #IMPLIED
	IsAddedAfterGen (True|False) #IMPLIED
	RsAttributesDefault (True|False) #IMPLIED
	OnScreenPick (True|False) #IMPLIED
	ClassName  CDATA   #IMPLIED
>
<!ELEMENT FKeyParamsClause  (#PCDATA)>

=== tylerm007/MetaRepos/Source/ClientApps/HTMLApps/HTML_ReposMaint.app/pAttribute.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Form SYSTEM "Form.dtd">
<Form
	DTDVersion="05.05.12"
	TargetLanguage="HTML"
	Archetype="Default"
	PositionTop="451.5625"
	PositionLeft="807.8125"
	PositionWidth="187.5"
	PositionHeight="54.6875"
	IsAddedAfterGen="False"
	HasCustomFormLayout="False"
	ObjectsUnusedByFormLayout="False"
	External="False"
	NoDataForm="False"
	ClassName="versata.pdx.html.VSPagePDX"
	ObjectsRemovedFromLayout="False"
	HTMLFileCheckSum="1305730055"
	>
	<FormCaption><![CDATA[Attribute]]></FormCaption>
	<ArchetypeExtendedProperties>
		<Property
			Name="Comments"
			Value=""
		/>
		<Property
			Name="CommentsTrailing"
			Value=""
		/>
		<Property
			Name="CrumbTrailEnabled"
			Value="true"
		/>
		<Property
			Name="CrumbTrailIncludesThisPage"
			Value="true"
		/>
		<Property
			Name="CrumbTrailRestartsHere"
			Value="false"
		/>
		<Property
			Name="CrumbTrailSeparator"
			Value="&gt;"
		/>
		<Property
			Name="ErrorStyle"
			Value="Popup"
		/>
		<Property
			Name="IncludeFooter"
			Value="false"
		/>
		<Property
			Name="IncludeHeader"
			Value="false"
		/>
		<Property
			Name="IncludeLeftBar"
			Value="false"
		/>
		<Property
			Name="IncludeRightBar"
			Value="false"
		/>
		<Property
			Name="ShowCancelButton"
			Value="true"
		/>
		<Property
			Name="ShowFormCaption"
			Value="true"
		/>
		<Property
			Name="ShowReturnButton"
			Value="true"
		/>
		<Property
			Name="TransitionsToHide"
			Value=""
		/>
	</ArchetypeExtendedProperties>
	<RecordSource
		RSID="1"
		Prefix="T1"
		BusinessObject="Attribute"
		RelnIsFromParent="False"
		DoesSourceAffectMe="False"
		DoIAffectSource="False"
		IsAddedAfterGen="False"
		RsAttributesDefault="True"
		ClassName="versata.pdx.html.DataSourcePDX"
		RecordSourceArchetype="Display"
		MaxGridRowCount="10"
		FetchedBlockRowCount="16"
		AllowDelete="True"
		AllowInsert="True"
		AllowUpdate="True"
		SaveMode="Immediate"
		PreFetchRowCount="False"
		>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<RSAttributesMeta>
			<DefaultAttributes>
				<RSDefaultAttribute ID="1" Name="RepositoryName" />
				<RSDefaultAttribute ID="2" Name="DataObjectName" />
				<RSDefaultAttribute ID="3" Name="AttrName" />
				<RSDefaultAttribute ID="4" Name="Persistent" />
				<RSDefaultAttribute ID="5" Name="PreventUserUpdate" />
				<RSDefaultAttribute ID="6" Name="ValueRequired" />
				<RSDefaultAttribute ID="7" Name="DataType" />
				<RSDefaultAttribute ID="8" Name="AttrSize" />
				<RSDefaultAttribute ID="9" Name="Description" />
				<RSDefaultAttribute ID="10" Name="Caption" />
				<RSDefaultAttribute ID="11" Name="Comments" />
				<RSDefaultAttribute ID="12" Name="Format" />
				<RSDefaultAttribute ID="13" Name="MicroHelp" />
				<RSDefaultAttribute ID="14" Name="Derivation_Cnt" />
				<RSDefaultAttribute ID="15" Name="Validation_Cnt" />
				<RSDefaultAttribute ID="16" Name="Formula_Cnt" />
				<RSDefaultAttribute ID="17" Name="Sum_Cnt" />
				<RSDefaultAttribute ID="18" Name="Count_Cnt" />
				<RSDefaultAttribute ID="19" Name="ParentRepl_Cnt" />
				<RSDefaultAttribute ID="20" Name="Precision" />
				<RSDefaultAttribute ID="21" Name="Scale" />
				<RSDefaultAttribute ID="22" Name="SQLDataType" />
			</DefaultAttributes>
			<ScalerAttributes>
				<RSAttribute Name="RepositoryName" Displayed="False" UnPlaced="False" />
				<RSAttribute Name="DataObjectName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="AttrName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Persistent" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="PreventUserUpdate" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ValueRequired" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="DataType" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="AttrSize" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Description" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Caption" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Comments" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Format" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="MicroHelp" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Derivation_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Validation_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Formula_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Sum_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Count_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ParentRepl_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Precision" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Scale" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="SQLDataType" Displayed="True" UnPlaced="False" />
			</ScalerAttributes>
		</RSAttributesMeta>
		<ArchetypeExtendedProperties>
			<Property
				Name="Caption"
				Value=""
			/>
			<Property
				Name="Comments"
				Value=""
			/>
			<Property
				Name="CommentsTrailing"
				Value="&lt;br&gt;"
			/>
			<Property
				Name="Cond0HideRecSrc"
				Value=""
			/>
			<Property
				Name="Cond1"
				Value=""
			/>
			<Property
				Name="Cond1Actions"
				Value=""
			/>
			<Property
				Name="Cond1Fields"
				Value=""
			/>
			<Property
				Name="Cond1Transitions"
				Value=""
			/>
			<Property
				Name="Cond2"
				Value=""
			/>
			<Property
				Name="Cond2Actions"
				Value=""
			/>
			<Property
				Name="Cond2Fields"
				Value=""
			/>
			<Property
				Name="Cond2Transitions"
				Value=""
			/>
			<Property
				Name="Cond3"
				Value=""
			/>
			<Property
				Name="Cond3Actions"
				Value=""
			/>
			<Property
				Name="Cond3Fields"
				Value=""
			/>
			<Property
				Name="Cond3Transitions"
				Value=""
			/>
			<Property
				Name="Cond4"
				Value=""
			/>
			<Property
				Name="Cond4Actions"
				Value=""
			/>
			<Property
				Name="Cond4Fields"
				Value=""
			/>
			<Property
				Name="Cond4Transitions"
				Value=""
			/>
			<Property
				Name="Cond5"
				Value=""
			/>
			<Property
				Name="Cond5Actions"
				Value=""
			/>
			<Property
				Name="Cond5Fields"
				Value=""
			/>
			<Property
				Name="Cond5Transitions"
				Value=""
			/>
			<Property
				Name="ConfirmDeleteMsg"
				Value="Delete record?"
			/>
			<Property
				Name="FieldCaptionPosition"
				Value="Left"
			/>
			<Property
				Name="FieldMaxLength"
				Value="50"
			/>
			<Property
				Name="FieldsDisplayedTogether"
				Value=""
			/>
			<Property
				Name="MaxNumberOfRows"
				Value="5"
			/>
			<Property
				Name="RequiredCaptionPrefix"
				Value=""
			/>
			<Property
				Name="RequiredCaptionSuffix"
				Value="*"
			/>
			<Property
				Name="ShowRSActions"
				Value="true"
			/>
			<Property
				Name="StartNewColsFields"
				Value=""
			/>
			<Property
				Name="TabCaption"
				Value=""
			/>
			<Property
				Name="TabGenerated"
				Value="true"
			/>
			<Property
				Name="TabImageHeight"
				Value=""
			/>
			<Property
				Name="TabImageOff"
				Value=""
			/>
			<Property
				Name="TabImageOn"
				Value=""
			/>
			<Property
				Name="TabImageWidth"
				Value=""
			/>
			<Property
				Name="TabSheetsEnabled"
				Value="true"
			/>
			<Property
				Name="TabSheetsInitialRS"
				Value=""
			/>
			<Property
				Name="UsePopupPicks"
				Value="true"
			/>
			<Property
				Name="ZoomFromRS"
				Value=""
			/>
		</ArchetypeExtendedProperties>
		<Transition
			FormTransNum="1"
			Prefix="T2"
			TargetFormName="pValidation"
			IsTargetInitialQueryMode="False"
			IsTargetInitialAddMode="False"
			IsVisibleAppline="True"
			IsAddedAfterGen="False"
			ClassName="PageNavigation"
			TargetFramesetPage=""
			TargetFrame=""
			FrameNameInFramesetPage=""
			RSID="2"
			BusinessObject="Validation"
			Relationship="ValidationAttr(Attribute)-Validations(Validation)"
			RelnIsFromParent="True"
			>
			<OrderByClause><![CDATA[ ]]></OrderByClause>
			<ParameterizedWhereClause><![CDATA[ [RepositoryName] = [?RepositoryName] and [DataObjectName] = [?DataObjectName] and [AttrName] = [?AttrName]]]></ParameterizedWhereClause>
			<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
		</Transition>
		<Transition
			FormTransNum="1"
			Prefix="T3"
			TargetFormName="pDerivation"
			IsTargetInitialQueryMode="False"
			IsTargetInitialAddMode="False"
			IsVisibleAppline="True"
			IsAddedAfterGen="False"
			ClassName="PageNavigation"
			TargetFramesetPage=""
			TargetFrame=""
			FrameNameInFramesetPage=""
			RSID="3"
			BusinessObject="Derivation"
			Relationship="DerivationAttr(Attribute)-Derivations(Derivation)"
			RelnIsFromParent="True"
			>
			<OrderByClause><![CDATA[ ]]></OrderByClause>
			<ParameterizedWhereClause><![CDATA[ [RepositoryName] = [?RepositoryName] and [DataObjectName] = [?DataObjectName] and [AttrName] = [?AttrName]]]></ParameterizedWhereClause>
			<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
		</Transition>
	</RecordSource>
</Form>

=== tylerm007/MetaRepos/Source/ClientApps/HTMLApps/Project1.app/pRelationship_Grid.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Form SYSTEM "Form.dtd">
<Form
	DTDVersion="05.05.12"
	TargetLanguage="HTML"
	Archetype="Default"
	PositionTop="325"
	PositionLeft="1.5625"
	PositionWidth="190.625"
	PositionHeight="43.75"
	IsAddedAfterGen="False"
	HasCustomFormLayout="False"
	ObjectsUnusedByFormLayout="False"
	External="False"
	NoDataForm="False"
	ClassName="versata.pdx.html.VSPagePDX"
	ObjectsRemovedFromLayout="False"
	HTMLFileCheckSum="524313688"
	>
	<FormCaption><![CDATA[Relationship(s)]]></FormCaption>
	<ArchetypeExtendedProperties>
		<Property
			Name="Comments"
			Value=""
		/>
		<Property
			Name="CommentsTrailing"
			Value=""
		/>
		<Property
			Name="CrumbTrailEnabled"
			Value="true"
		/>
		<Property
			Name="CrumbTrailIncludesThisPage"
			Value="true"
		/>
		<Property
			Name="CrumbTrailRestartsHere"
			Value="false"
		/>
		<Property
			Name="CrumbTrailSeparator"
			Value="&gt;"
		/>
		<Property
			Name="ErrorStyle"
			Value="Popup"
		/>
		<Property
			Name="IncludeFooter"
			Value="false"
		/>
		<Property
			Name="IncludeHeader"
			Value="false"
		/>
		<Property
			Name="IncludeLeftBar"
			Value="false"
		/>
		<Property
			Name="IncludeRightBar"
			Value="false"
		/>
		<Property
			Name="ShowCancelButton"
			Value="true"
		/>
		<Property
			Name="ShowFormCaption"
			Value="true"
		/>
		<Property
			Name="ShowReturnButton"
			Value="true"
		/>
		<Property
			Name="TransitionsToHide"
			Value=""
		/>
	</ArchetypeExtendedProperties>
	<RecordSource
		RSID="1"
		Prefix="T1"
		BusinessObject="Relationship"
		RelnIsFromParent="False"
		DoesSourceAffectMe="False"
		DoIAffectSource="False"
		IsAddedAfterGen="False"
		RsAttributesDefault="True"
		ClassName="versata.pdx.html.DataSourcePDX"
		RecordSourceArchetype="Grid"
		MaxGridRowCount="10"
		FetchedBlockRowCount="16"
		AllowDelete="False"
		AllowInsert="False"
		AllowUpdate="False"
		SaveMode="Immediate"
		PreFetchRowCount="False"
		>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<RSAttributesMeta>
			<DefaultAttributes>
				<RSDefaultAttribute ID="1" Name="RepositoryName" />
				<RSDefaultAttribute ID="2" Name="RelationshipName" />
				<RSDefaultAttribute ID="3" Name="ParentDOName" />
				<RSDefaultAttribute ID="4" Name="ParentRoleName" />
				<RSDefaultAttribute ID="5" Name="ChildDOName" />
				<RSDefaultAttribute ID="6" Name="ChildRoleName" />
				<RSDefaultAttribute ID="7" Name="isEnforce" />
				<RSDefaultAttribute ID="8" Name="ParentAttribute" />
				<RSDefaultAttribute ID="9" Name="ChildAttribute" />
				<RSDefaultAttribute ID="10" Name="RolePlayer_CNT" />
			</DefaultAttributes>
			<GridAttributes>
				<RSAttribute Name="RepositoryName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="RelationshipName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ParentDOName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ParentRoleName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ChildDOName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ChildRoleName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="isEnforce" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ParentAttribute" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ChildAttribute" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="RolePlayer_CNT" Displayed="True" UnPlaced="False" />
			</GridAttributes>
		</RSAttributesMeta>
		<ArchetypeExtendedProperties>
			<Property
				Name="AltRowColor"
				Value="#DFE5EF"
			/>
			<Property
				Name="Caption"
				Value=""
			/>
			<Property
				Name="Comments"
				Value=""
			/>
			<Property
				Name="CommentsTrailing"
				Value="&lt;br&gt;"
			/>
			<Property
				Name="Cond0HideRecSrc"
				Value=""
			/>
			<Property
				Name="Cond1"
				Value=""
			/>
			<Property
				Name="Cond1Actions"
				Value=""
			/>
			<Property
				Name="Cond2"
				Value=""
			/>
			<Property
				Name="Cond2Actions"
				Value=""
			/>
			<Property
				Name="Cond3"
				Value=""
			/>
			<Property
				Name="Cond3Actions"
				Value=""
			/>
			<Property
				Name="Cond4"
				Value=""
			/>
			<Property
				Name="Cond4Actions"
				Value=""
			/>
			<Property
				Name="Cond5"
				Value=""
			/>
			<Property
				Name="Cond5Actions"
				Value=""
			/>
			<Property
				Name="ConfirmDeleteMsg"
				Value="Delete record?"
			/>
			<Property
				Name="NoDataMessage"
				Value="&lt;br&gt;&lt;center&gt;&lt;b&gt;No records found!&lt;/b&gt;&lt;/center&gt;&lt;br&gt;"
			/>
			<Property
				Name="ShowHeader"
				Value="true"
			/>
			<Property
				Name="ShowRowCount"
				Value="true"
			/>
			<Property
				Name="ShowRowSelector"
				Value="true"
			/>
			<Property
				Name="SortableHeader"
				Value="true"
			/>
			<Property
				Name="TabCaption"
				Value=""
			/>
			<Property
				Name="TabGenerated"
				Value="true"
			/>
			<Property
				Name="TabImageHeight"
				Value=""
			/>
			<Property
				Name="TabImageOff"
				Value=""
			/>
			<Property
				Name="TabImageOn"
				Value=""
			/>
			<Property
				Name="TabImageWidth"
				Value=""
			/>
			<Property
				Name="UsePopupPicks"
				Value="true"
			/>
		</ArchetypeExtendedProperties>
	</RecordSource>
</Form>

=== tylerm007/MetaRepos/Source/ClientApps/HTMLApps/Project1.app/pIndexAttr_Grid.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Form SYSTEM "Form.dtd">
<Form
	DTDVersion="05.05.12"
	TargetLanguage="HTML"
	Archetype="Default"
	PositionTop="325"
	PositionLeft="570"
	PositionWidth="163.75"
	PositionHeight="43.75"
	IsAddedAfterGen="False"
	HasCustomFormLayout="False"
	ObjectsUnusedByFormLayout="False"
	External="False"
	NoDataForm="False"
	ClassName="versata.pdx.html.VSPagePDX"
	ObjectsRemovedFromLayout="False"
	HTMLFileCheckSum="1782378395"
	>
	<FormCaption><![CDATA[IndexAttr(s)]]></FormCaption>
	<ArchetypeExtendedProperties>
		<Property
			Name="Comments"
			Value=""
		/>
		<Property
			Name="CommentsTrailing"
			Value=""
		/>
		<Property
			Name="CrumbTrailEnabled"
			Value="true"
		/>
		<Property
			Name="CrumbTrailIncludesThisPage"
			Value="true"
		/>
		<Property
			Name="CrumbTrailRestartsHere"
			Value="false"
		/>
		<Property
			Name="CrumbTrailSeparator"
			Value="&gt;"
		/>
		<Property
			Name="ErrorStyle"
			Value="Popup"
		/>
		<Property
			Name="IncludeFooter"
			Value="false"
		/>
		<Property
			Name="IncludeHeader"
			Value="false"
		/>
		<Property
			Name="IncludeLeftBar"
			Value="false"
		/>
		<Property
			Name="IncludeRightBar"
			Value="false"
		/>
		<Property
			Name="ShowCancelButton"
			Value="true"
		/>
		<Property
			Name="showFormCaption"
			Value="true"
		/>
		<Property
			Name="ShowReturnButton"
			Value="true"
		/>
		<Property
			Name="TransitionsToHide"
			Value=""
		/>
	</ArchetypeExtendedProperties>
	<RecordSource
		RSID="1"
		Prefix="T1"
		BusinessObject="IndexAttr"
		RelnIsFromParent="False"
		DoesSourceAffectMe="False"
		DoIAffectSource="False"
		IsAddedAfterGen="False"
		RsAttributesDefault="True"
		ClassName="versata.pdx.html.DataSourcePDX"
		RecordSourceArchetype="Grid"
		MaxGridRowCount="10"
		FetchedBlockRowCount="16"
		AllowDelete="False"
		AllowInsert="False"
		AllowUpdate="False"
		SaveMode="Immediate"
		PreFetchRowCount="False"
		>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<RSAttributesMeta>
			<DefaultAttributes>
				<RSDefaultAttribute ID="1" Name="RepositoryName" />
				<RSDefaultAttribute ID="2" Name="DataObjectName" />
				<RSDefaultAttribute ID="3" Name="IndexName" />
				<RSDefaultAttribute ID="4" Name="IndexAttrName" />
			</DefaultAttributes>
			<GridAttributes>
				<RSAttribute Name="RepositoryName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="DataObjectName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="IndexName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="IndexAttrName" Displayed="True" UnPlaced="False" />
			</GridAttributes>
		</RSAttributesMeta>
		<ArchetypeExtendedProperties>
			<Property
				Name="AltRowColor"
				Value="#DFE5EF"
			/>
			<Property
				Name="Caption"
				Value=""
			/>
			<Property
				Name="Comments"
				Value=""
			/>
			<Property
				Name="CommentsTrailing"
				Value="&lt;br&gt;"
			/>
			<Property
				Name="Cond0HideRecSrc"
				Value=""
			/>
			<Property
				Name="Cond1"
				Value=""
			/>
			<Property
				Name="Cond1Actions"
				Value=""
			/>
			<Property
				Name="Cond2"
				Value=""
			/>
			<Property
				Name="Cond2Actions"
				Value=""
			/>
			<Property
				Name="Cond3"
				Value=""
			/>
			<Property
				Name="Cond3Actions"
				Value=""
			/>
			<Property
				Name="Cond4"
				Value=""
			/>
			<Property
				Name="Cond4Actions"
				Value=""
			/>
			<Property
				Name="Cond5"
				Value=""
			/>
			<Property
				Name="Cond5Actions"
				Value=""
			/>
			<Property
				Name="ConfirmDeleteMsg"
				Value="Delete record?"
			/>
			<Property
				Name="NoDataMessage"
				Value="&lt;br&gt;&lt;center&gt;&lt;b&gt;No records found!&lt;/b&gt;&lt;/center&gt;&lt;br&gt;"
			/>
			<Property
				Name="ShowHeader"
				Value="true"
			/>
			<Property
				Name="ShowRowCount"
				Value="true"
			/>
			<Property
				Name="ShowRowSelector"
				Value="true"
			/>
			<Property
				Name="SortableHeader"
				Value="true"
			/>
			<Property
				Name="TabCaption"
				Value=""
			/>
			<Property
				Name="TabGenerated"
				Value="true"
			/>
			<Property
				Name="TabImageHeight"
				Value=""
			/>
			<Property
				Name="TabImageOff"
				Value=""
			/>
			<Property
				Name="TabImageOn"
				Value=""
			/>
			<Property
				Name="TabImageWidth"
				Value=""
			/>
			<Property
				Name="UsePopupPicks"
				Value="true"
			/>
		</ArchetypeExtendedProperties>
	</RecordSource>
</Form>
