=== tylerm007/MetaRepos/Source/ClientApps/JavaApps/ObjectDiff.app/Form.dtd
<!ELEMENT Form ( FormCaption | Description | ArchetypeExtendedProperties | ExtendedProperties | FormLayout | RecordSource | Transition  )* >
<!ATTLIST Form 
	TargetLanguage CDATA #REQUIRED 
	Archetype CDATA #IMPLIED 
	PositionTop CDATA   #IMPLIED
	PositionLeft CDATA   #IMPLIED
	PositionWidth CDATA  #IMPLIED
	PositionHeight CDATA   #IMPLIED
	IsAddedAfterGen (True|False) #IMPLIED
	DirtyFlag (b|d|i|BLANK)  #IMPLIED 
	HasCustomFormLayout (True|False)  #IMPLIED
	ObjectsUnusedByFormLayout (True|False) #IMPLIED
	ClassName CDATA #IMPLIED
	ObjectsRemovedFromLayout  (True|False) #IMPLIED
	External (True|False) #IMPLIED
	NoDataForm (True|False) #IMPLIED
	DTDVersion CDATA #REQUIRED
	HTMLFileCheckSum CDATA #IMPLIED
>

<!ELEMENT FormCaption (#PCDATA) >
<!ELEMENT Description (#PCDATA) >
<!ELEMENT ArchetypeExtendedProperties (Property)* >
<!ELEMENT ExtendedProperties (Property)* >
<!ELEMENT FormLayout (#PCDATA) >

<!ELEMENT Property EMPTY>
<!ATTLIST Property 
	Name CDATA #REQUIRED
	Value CDATA #REQUIRED
>

<!ELEMENT RecordSource (OrderByClause | ParameterizedWhereClause | AdditionalWhereClause | ArchetypeExtendedProperties | ExtendedProperties | Description | RSAttributesMeta | RecordSource | PickObject | Transition )* >
<!ATTLIST RecordSource 
	RSID CDATA #REQUIRED
	Prefix CDATA #REQUIRED
	BusinessObject CDATA #REQUIRED
	RecordSourceArchetype CDATA #REQUIRED
	Relationship CDATA #IMPLIED
	RelnIsFromParent (True|False) #IMPLIED
	DoesSourceAffectMe (True|False) #IMPLIED
	DoIAffectSource (True|False) #IMPLIED
	IsAddedAfterGen (True|False) #IMPLIED
	RsAttributesDefault (True|False) #IMPLIED
	ClassName   CDATA  #IMPLIED
	MaxGridRowCount CDATA  #IMPLIED   
	FetchedBlockRowCount CDATA  #IMPLIED
	AllowDelete  (True|False) #IMPLIED
	AllowInsert  (True|False) #IMPLIED
	AllowUpdate  (True|False) #IMPLIED
	SaveMode (Buffered|Immediate) #IMPLIED
	PreFetchRowCount  (True|False) #IMPLIED
	ParentAlias  CDATA  #IMPLIED
	ChildAlias   CDATA  #IMPLIED
>

<!ELEMENT OrderByClause  (#PCDATA)>
<!ELEMENT ParameterizedWhereClause  (#PCDATA)>
<!ELEMENT AdditionalWhereClause  (#PCDATA)>
<!ELEMENT RSAttributesMeta  ( DefaultAttributes | ScalerAttributes | GridAttributes )* >
<!ELEMENT DefaultAttributes (RSDefaultAttribute)* >
<!ELEMENT ScalerAttributes (RSAttribute)* >
<!ELEMENT GridAttributes (RSAttribute)* >
<!ELEMENT RSDefaultAttribute EMPTY >
<!ATTLIST RSDefaultAttribute
	ID CDATA #REQUIRED
	Name CDATA #REQUIRED
>
<!ELEMENT RSAttribute EMPTY >
<!ATTLIST RSAttribute
	Name CDATA #REQUIRED
	Displayed CDATA #IMPLIED
	UnPlaced CDATA #IMPLIED
	Archetype CDATA #IMPLIED
	TransitionToUse CDATA #IMPLIED
>

<!ELEMENT Transition (OrderByClause | ParameterizedWhereClause | AdditionalWhereClause | ExtendedProperties | Description)* >
<!ATTLIST Transition
	FormTransNum  CDATA #IMPLIED
	BusinessObject CDATA #IMPLIED
	RSID CDATA #IMPLIED
	Prefix CDATA #REQUIRED
	TargetFormName CDATA #REQUIRED
	IsTargetInitialQueryMode  (True|False) #IMPLIED
	IsTargetInitialAddMode (True|False) #IMPLIED
	IsVisibleAppline (True|False) #IMPLIED
	Relationship CDATA #IMPLIED
	RelnIsFromParent CDATA #IMPLIED
	IsAddedAfterGen (True|False) #IMPLIED
	FormTransCaption CDATA  #IMPLIED
	ClassName CDATA #IMPLIED
	TargetFramesetPage CDATA #IMPLIED  
	TargetFrame CDATA #IMPLIED   
	FrameNameInFramesetPage CDATA #IMPLIED
>

<!ELEMENT PickObject (OrderByClause | FKeyParamsClause | AdditionalWhereClause | ExtendedProperties | Description | RSAttributesMeta )* >
<!ATTLIST PickObject 
	RSID CDATA #REQUIRED
	Prefix CDATA #REQUIRED
	BusinessObject CDATA #REQUIRED
	Relationship CDATA #IMPLIED
	RelnIsFromParent (True|False) #IMPLIED
	OrderByClause CDATA   #IMPLIED
	PickTargetFormName CDATA #IMPLIED
	DoesSourceAffectMe CDATA   #IMPLIED
	DoIAffectSource CDATA   #IMPLIED
	IsAddedAfterGen (True|False) #IMPLIED
	RsAttributesDefault (True|False) #IMPLIED
	OnScreenPick (True|False) #IMPLIED
	ClassName  CDATA   #IMPLIED
>
<!ELEMENT FKeyParamsClause  (#PCDATA)>

=== tylerm007/MetaRepos/Source/ClientApps/HTMLApps/HTML_ReposMaint.app/pDataObject_Grid.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Form SYSTEM "Form.dtd">
<Form
	DTDVersion="05.05.12"
	TargetLanguage="HTML"
	Archetype="Default"
	PositionTop="340.625"
	PositionLeft="351.5625"
	PositionWidth="187.5"
	PositionHeight="54.6875"
	IsAddedAfterGen="False"
	HasCustomFormLayout="False"
	ObjectsUnusedByFormLayout="False"
	External="False"
	NoDataForm="False"
	ClassName="versata.pdx.html.VSPagePDX"
	ObjectsRemovedFromLayout="False"
	HTMLFileCheckSum="-699624818"
	>
	<FormCaption><![CDATA[DataObject(s)]]></FormCaption>
	<ArchetypeExtendedProperties>
		<Property
			Name="Comments"
			Value=""
		/>
		<Property
			Name="CommentsTrailing"
			Value=""
		/>
		<Property
			Name="CrumbTrailEnabled"
			Value="true"
		/>
		<Property
			Name="CrumbTrailIncludesThisPage"
			Value="true"
		/>
		<Property
			Name="CrumbTrailRestartsHere"
			Value="false"
		/>
		<Property
			Name="CrumbTrailSeparator"
			Value="&gt;"
		/>
		<Property
			Name="ErrorStyle"
			Value="Popup"
		/>
		<Property
			Name="IncludeFooter"
			Value="false"
		/>
		<Property
			Name="IncludeHeader"
			Value="false"
		/>
		<Property
			Name="IncludeLeftBar"
			Value="false"
		/>
		<Property
			Name="IncludeRightBar"
			Value="false"
		/>
		<Property
			Name="ShowCancelButton"
			Value="true"
		/>
		<Property
			Name="ShowFormCaption"
			Value="true"
		/>
		<Property
			Name="ShowReturnButton"
			Value="true"
		/>
		<Property
			Name="TransitionsToHide"
			Value=""
		/>
	</ArchetypeExtendedProperties>
	<RecordSource
		RSID="1"
		Prefix="T1"
		BusinessObject="DataObject"
		RelnIsFromParent="False"
		DoesSourceAffectMe="False"
		DoIAffectSource="False"
		IsAddedAfterGen="False"
		RsAttributesDefault="True"
		ClassName="versata.pdx.html.DataSourcePDX"
		RecordSourceArchetype="Grid"
		MaxGridRowCount="10"
		FetchedBlockRowCount="16"
		AllowDelete="False"
		AllowInsert="False"
		AllowUpdate="False"
		SaveMode="Immediate"
		PreFetchRowCount="False"
		>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<RSAttributesMeta>
			<DefaultAttributes>
				<RSDefaultAttribute ID="1" Name="RepositoryName" />
				<RSDefaultAttribute ID="2" Name="DataObjectName" />
				<RSDefaultAttribute ID="3" Name="isCodedValueList" />
				<RSDefaultAttribute ID="4" Name="SuperClass" />
				<RSDefaultAttribute ID="5" Name="SingularCaption" />
				<RSDefaultAttribute ID="6" Name="PluralCaption" />
				<RSDefaultAttribute ID="7" Name="Description" />
				<RSDefaultAttribute ID="8" Name="Attr_Cnt" />
				<RSDefaultAttribute ID="9" Name="Constraint_Cnt" />
				<RSDefaultAttribute ID="10" Name="Action_Cnt" />
				<RSDefaultAttribute ID="11" Name="ParentReln_Cnt" />
				<RSDefaultAttribute ID="12" Name="ChildReln_Cnt" />
				<RSDefaultAttribute ID="13" Name="CountQueryObj" />
				<RSDefaultAttribute ID="14" Name="Gen_Lines_Cnt" />
				<RSDefaultAttribute ID="15" Name="User_Line_Cnt" />
				<RSDefaultAttribute ID="16" Name="Gen_Method_Cnt" />
				<RSDefaultAttribute ID="17" Name="User_Method_Cnt" />
				<RSDefaultAttribute ID="18" Name="Total_Line_Cnt" />
				<RSDefaultAttribute ID="19" Name="Total_Method_Cnt" />
				<RSDefaultAttribute ID="20" Name="Gen_Line_Pct" />
				<RSDefaultAttribute ID="21" Name="User_Line_Pct" />
				<RSDefaultAttribute ID="22" Name="Gen_Method_Pct" />
				<RSDefaultAttribute ID="23" Name="User_Method_Pct" />
				<RSDefaultAttribute ID="24" Name="InternalPathName" />
			</DefaultAttributes>
			<GridAttributes>
				<RSAttribute Name="RepositoryName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="DataObjectName" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="isCodedValueList" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="SuperClass" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="SingularCaption" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="PluralCaption" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Description" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Attr_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Constraint_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Action_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ParentReln_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="ChildReln_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="CountQueryObj" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Gen_Lines_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="User_Line_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Gen_Method_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="User_Method_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Total_Line_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Total_Method_Cnt" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Gen_Line_Pct" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="User_Line_Pct" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Gen_Method_Pct" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="User_Method_Pct" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="InternalPathName" Displayed="True" UnPlaced="False" />
			</GridAttributes>
		</RSAttributesMeta>
		<ArchetypeExtendedProperties>
			<Property
				Name="AltRowColor"
				Value="#EFEFEF"
			/>
			<Property
				Name="Caption"
				Value=""
			/>
			<Property
				Name="Comments"
				Value=""
			/>
			<Property
				Name="CommentsTrailing"
				Value="&lt;br&gt;"
			/>
			<Property
				Name="Cond0HideRecSrc"
				Value=""
			/>
			<Property
				Name="Cond1"
				Value=""
			/>
			<Property
				Name="Cond1Actions"
				Value=""
			/>
			<Property
				Name="Cond2"
				Value=""
			/>
			<Property
				Name="Cond2Actions"
				Value=""
			/>
			<Property
				Name="Cond3"
				Value=""
			/>
			<Property
				Name="Cond3Actions"
				Value=""
			/>
			<Property
				Name="Cond4"
				Value=""
			/>
			<Property
				Name="Cond4Actions"
				Value=""
			/>
			<Property
				Name="Cond5"
				Value=""
			/>
			<Property
				Name="Cond5Actions"
				Value=""
			/>
			<Property
				Name="ConfirmDeleteMsg"
				Value="Delete record?"
			/>
			<Property
				Name="NoDataMessage"
				Value="&lt;br&gt;&lt;center&gt;&lt;b&gt;No records found!&lt;/b&gt;&lt;/center&gt;&lt;br&gt;"
			/>
			<Property
				Name="ShowHeader"
				Value="true"
			/>
			<Property
				Name="ShowRowCount"
				Value="true"
			/>
			<Property
				Name="ShowRowSelector"
				Value="true"
			/>
			<Property
				Name="SortableHeader"
				Value="true"
			/>
			<Property
				Name="TabCaption"
				Value=""
			/>
			<Property
				Name="TabGenerated"
				Value="true"
			/>
			<Property
				Name="TabImageHeight"
				Value=""
			/>
			<Property
				Name="TabImageOff"
				Value=""
			/>
			<Property
				Name="TabImageOn"
				Value=""
			/>
			<Property
				Name="TabImageWidth"
				Value=""
			/>
			<Property
				Name="UsePopupPicks"
				Value="true"
			/>
		</ArchetypeExtendedProperties>
		<Transition
			FormTransNum="1"
			Prefix="T2"
			TargetFormName="pDataObject"
			IsTargetInitialQueryMode="False"
			IsTargetInitialAddMode="False"
			IsVisibleAppline="True"
			IsAddedAfterGen="False"
			ClassName="PageNavigation"
			TargetFramesetPage=""
			TargetFrame=""
			FrameNameInFramesetPage=""
			>
		</Transition>
		<Transition
			FormTransNum="1"
			Prefix="T3"
			TargetFormName="pAttribute_Grid"
			IsTargetInitialQueryMode="False"
			IsTargetInitialAddMode="False"
			IsVisibleAppline="True"
			IsAddedAfterGen="False"
			ClassName="PageNavigation"
			TargetFramesetPage=""
			TargetFrame=""
			FrameNameInFramesetPage=""
			RSID="2"
			BusinessObject="Attribute"
			Relationship="DataObject(DataObject)-Attributes(Attribute)"
			RelnIsFromParent="True"
			>
			<OrderByClause><![CDATA[ ]]></OrderByClause>
			<ParameterizedWhereClause><![CDATA[ [RepositoryName] = [?RepositoryName] and [DataObjectName] = [?DataObjectName]]]></ParameterizedWhereClause>
			<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
		</Transition>
		<Transition
			FormTransNum="1"
			Prefix="T4"
			TargetFormName="pAction_Grid"
			IsTargetInitialQueryMode="False"
			IsTargetInitialAddMode="False"
			IsVisibleAppline="True"
			IsAddedAfterGen="False"
			ClassName="PageNavigation"
			TargetFramesetPage=""
			TargetFrame=""
			FrameNameInFramesetPage=""
			RSID="3"
			BusinessObject="Action"
			Relationship="ActionReposiotry(DataObject)-Actions(Action)"
			RelnIsFromParent="True"
			>
			<OrderByClause><![CDATA[ ]]></OrderByClause>
			<ParameterizedWhereClause><![CDATA[ [RepositoryName] = [?RepositoryName] and [DataObjectName] = [?DataObjectName]]]></ParameterizedWhereClause>
			<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
		</Transition>
		<Transition
			FormTransNum="1"
			Prefix="T5"
			TargetFormName="pConstraint_Grid"
			IsTargetInitialQueryMode="False"
			IsTargetInitialAddMode="False"
			IsVisibleAppline="True"
			IsAddedAfterGen="False"
			ClassName="PageNavigation"
			TargetFramesetPage=""
			TargetFrame=""
			FrameNameInFramesetPage=""
			RSID="4"
			BusinessObject="Constraint"
			Relationship="ConstraintRepository(DataObject)-Constraints(Constraint)"
			RelnIsFromParent="True"
			>
			<OrderByClause><![CDATA[ ]]></OrderByClause>
			<ParameterizedWhereClause><![CDATA[ [RepositoryName] = [?RepositoryName] and [DataObjectName] = [?DataObjectName]]]></ParameterizedWhereClause>
			<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
		</Transition>
	</RecordSource>
</Form>

=== tylerm007/MetaRepos/Source/ClientApps/JavaApps/JavaSample.app/StartupForm.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Form SYSTEM "Form.dtd">
<Form
	DTDVersion="05.05.12"
	TargetLanguage="Java"
	Archetype="Startup"
	PositionTop="20.3125"
	PositionLeft="23.4375"
	PositionWidth="187.5"
	PositionHeight="54.6875"
	IsAddedAfterGen="False"
	HasCustomFormLayout="False"
	ObjectsUnusedByFormLayout="False"
	External="False"
	NoDataForm="False"
	>
	<FormCaption><![CDATA[StartupForm]]></FormCaption>
	<Transition
		FormTransNum="1"
		Prefix="T1"
		TargetFormName="fRepository"
		IsTargetInitialQueryMode="False"
		IsTargetInitialAddMode="False"
		IsVisibleAppline="True"
		IsAddedAfterGen="False"
		ClassName="PageNavigation"
		RSID="1"
		BusinessObject="Repository"
		RelnIsFromParent="True"
		>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
	</Transition>
	<Transition
		FormTransNum="1"
		Prefix="T2"
		TargetFormName="fReposDiff"
		IsTargetInitialQueryMode="False"
		IsTargetInitialAddMode="False"
		IsVisibleAppline="True"
		IsAddedAfterGen="False"
		ClassName="PageNavigation"
		RSID="5"
		BusinessObject="ReposDiff"
		RelnIsFromParent="True"
		>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
	</Transition>
	<Transition
		FormTransNum="1"
		Prefix="T3"
		TargetFormName="fOtherFile_Grid"
		IsTargetInitialQueryMode="False"
		IsTargetInitialAddMode="False"
		IsVisibleAppline="True"
		IsAddedAfterGen="False"
		ClassName="PageNavigation"
		RSID="6"
		BusinessObject="OtherFile"
		RelnIsFromParent="True"
		>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
	</Transition>
	<Transition
		FormTransNum="1"
		Prefix="T4"
		TargetFormName="fReposName"
		IsTargetInitialQueryMode="False"
		IsTargetInitialAddMode="False"
		IsVisibleAppline="True"
		IsAddedAfterGen="False"
		ClassName="PageNavigation"
		RSID="8"
		BusinessObject="ReposName"
		RelnIsFromParent="True"
		>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
	</Transition>
	<Transition
		FormTransNum="1"
		Prefix="T5"
		TargetFormName="fReposGroups"
		IsTargetInitialQueryMode="False"
		IsTargetInitialAddMode="False"
		IsVisibleAppline="True"
		IsAddedAfterGen="False"
		ClassName="PageNavigation"
		RSID="9"
		BusinessObject="ReposName"
		RelnIsFromParent="True"
		>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
	</Transition>
	<FormLayout><![CDATA[BEGIN .VSForm StartupForm
  ImageFile = "paper10.gif"
  ClassName = "VSForm"
  BackColor = 0xc0c0c0
Width=131
  ImageDisplayStyle = Stretched
  Title = ""
  Enable = True
  ForeColor = 0x000000
  HelpURL = ""
  ToolTip = ""
  Visible = True
  Tag = "_$$_"
Height=533
  AnchorForm = "LEFT"
  Style = "Child"
  Name = "StartupForm"
  Extended = ""
  DisplayTitleBar = False
  BeginProperty VSFont 
    FontName  = "Helvetica"
    FontSize  = 12
    FontStyleBold  = False
    FontStyleItalic  = False
  EndProperty 
    BEGIN .VSImageButton ibtT1fRepository
     ImageFile = ""
Top=8
      ClassName = "VSImageButton"
      StatusBarText = ""
      FormTransitionProperties = ""
           DataSource = "(None)"
      BackColor = 0xebebeb
Width=114
      Enable = True
      ForeColor = 0x000000
      HelpURL = ""
      ToolTip = "Repository"
      Visible = True
      Tag = "_$$_"
      Action = ""
TabOrder = 0
Height=82
Left=5
      AutoSize = False
      TabStop = True
      Border = "RAISED_BORDER"
      Extended = ""
      Name = "ibtT1fRepository"
      AutoLabel = False
     FormTransition = 10001,T1Repository_fRepository
      BeginProperty VSFont 
        FontName  = "Helvetica"
        FontSize  = 12
        FontStyleBold  = False
        FontStyleItalic  = False
      EndProperty 
      DisplayStyle = Stretched
     Label = "Repository"
      END
    BEGIN .VSImageButton ibtT2fReposDiff
     ImageFile = ""
Top=103
      ClassName = "VSImageButton"
      StatusBarText = ""
      FormTransitionProperties = ""
           DataSource = "(None)"
      BackColor = 0xebebeb
Width=114
      Enable = True
      ForeColor = 0x000000
      HelpURL = ""
      ToolTip = "ReposDiff"
      Visible = True
      Tag = "_$$_"
      Action = ""
TabOrder = 1
Height=82
Left=5
      AutoSize = False
      TabStop = True
      Border = "RAISED_BORDER"
      Extended = ""
      Name = "ibtT2fReposDiff"
      AutoLabel = False
     FormTransition = 50001,T2ReposDiff_fReposDiff
      BeginProperty VSFont 
        FontName  = "Helvetica"
        FontSize  = 12
        FontStyleBold  = False
        FontStyleItalic  = False
      EndProperty 
      DisplayStyle = Stretched
     Label = "ReposDiff"
      END
    BEGIN .VSImageButton ibtT3fOtherFile_Grid
     ImageFile = ""
Top=198
      ClassName = "VSImageButton"
      StatusBarText = ""
      FormTransitionProperties = ""
           DataSource = "(None)"
      BackColor = 0xebebeb
Width=114
      Enable = True
      ForeColor = 0x000000
      HelpURL = ""
      ToolTip = "OtherFile(s)"
      Visible = True
      Tag = "_$$_"
      Action = ""
TabOrder = 2
Height=82
Left=5
      AutoSize = False
      TabStop = True
      Border = "RAISED_BORDER"
      Extended = ""
      Name = "ibtT3fOtherFile_Grid"
      AutoLabel = False
     FormTransition = 60001,T3OtherFile_fOtherFile_Grid
      BeginProperty VSFont 
        FontName  = "Helvetica"
        FontSize  = 12
        FontStyleBold  = False
        FontStyleItalic  = False
      EndProperty 
      DisplayStyle = Stretched
     Label = "OtherFile(s)"
      END
    BEGIN .VSImageButton ibtT4fReposName
     ImageFile = ""
Top=293
      ClassName = "VSImageButton"
      StatusBarText = ""
      FormTransitionProperties = ""
           DataSource = "(None)"
      BackColor = 0xebebeb
Width=114
      Enable = True
      ForeColor = 0x000000
      HelpURL = ""
      ToolTip = "Repository Version"
      Visible = True
      Tag = "_$$_"
      Action = ""
TabOrder = 3
Height=82
Left=5
      AutoSize = False
      TabStop = True
      Border = "RAISED_BORDER"
      Extended = ""
      Name = "ibtT4fReposName"
      AutoLabel = False
     FormTransition = 80001,T4ReposName_fReposName
      BeginProperty VSFont 
        FontName  = "Helvetica"
        FontSize  = 12
        FontStyleBold  = False
        FontStyleItalic  = False
      EndProperty 
      DisplayStyle = Stretched
     Label = "Repository Version"
      END
    BEGIN .VSImageButton ibtT5fReposGroups
     ImageFile = ""
Top=388
      ClassName = "VSImageButton"
      StatusBarText = ""
      FormTransitionProperties = ""
           DataSource = "(None)"
      BackColor = 0xebebeb
Width=114
      Enable = True
      ForeColor = 0x000000
      HelpURL = ""
      ToolTip = "Groups"
      Visible = True
      Tag = "_$$_"
      Action = ""
TabOrder = 4
Height=82
Left=5
      AutoSize = False
      TabStop = True
      Border = "RAISED_BORDER"
      Extended = ""
      Name = "ibtT5fReposGroups"
      AutoLabel = False
     FormTransition = 90001,T5ReposName_fReposGroups
      BeginProperty VSFont 
        FontName  = "Helvetica"
        FontSize  = 12
        FontStyleBold  = False
        FontStyleItalic  = False
      EndProperty 
      DisplayStyle = Stretched
     Label = "Groups"
      END
  END
]]></FormLayout>
</Form>

=== tylerm007/MetaRepos/Source/ClientApps/HTMLApps/HTML_ReposMaint.app/pReposVersion_Grid.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Form SYSTEM "Form.dtd">
<Form
	DTDVersion="05.05.12"
	TargetLanguage="HTML"
	Archetype="Default"
	PositionTop="104.6875"
	PositionLeft="325"
	PositionWidth="215.625"
	PositionHeight="54.6875"
	IsAddedAfterGen="False"
	HasCustomFormLayout="False"
	ObjectsUnusedByFormLayout="False"
	External="False"
	NoDataForm="False"
	ClassName="versata.pdx.html.VSPagePDX"
	ObjectsRemovedFromLayout="False"
	HTMLFileCheckSum="659159335"
	>
	<FormCaption><![CDATA[Version]]></FormCaption>
	<ArchetypeExtendedProperties>
		<Property
			Name="Comments"
			Value=""
		/>
		<Property
			Name="CommentsTrailing"
			Value=""
		/>
		<Property
			Name="CrumbTrailEnabled"
			Value="true"
		/>
		<Property
			Name="CrumbTrailIncludesThisPage"
			Value="true"
		/>
		<Property
			Name="CrumbTrailRestartsHere"
			Value="false"
		/>
		<Property
			Name="CrumbTrailSeparator"
			Value="&gt;"
		/>
		<Property
			Name="ErrorStyle"
			Value="Popup"
		/>
		<Property
			Name="IncludeFooter"
			Value="false"
		/>
		<Property
			Name="IncludeHeader"
			Value="false"
		/>
		<Property
			Name="IncludeLeftBar"
			Value="false"
		/>
		<Property
			Name="IncludeRightBar"
			Value="false"
		/>
		<Property
			Name="ShowCancelButton"
			Value="true"
		/>
		<Property
			Name="ShowFormCaption"
			Value="true"
		/>
		<Property
			Name="ShowReturnButton"
			Value="true"
		/>
		<Property
			Name="TransitionsToHide"
			Value=""
		/>
	</ArchetypeExtendedProperties>
	<RecordSource
		RSID="1"
		Prefix="T1"
		BusinessObject="ReposVersion"
		RelnIsFromParent="False"
		DoesSourceAffectMe="False"
		DoIAffectSource="False"
		IsAddedAfterGen="False"
		RsAttributesDefault="False"
		ClassName="versata.pdx.html.DataSourcePDX"
		RecordSourceArchetype="GridUpdatable"
		MaxGridRowCount="10"
		FetchedBlockRowCount="16"
		AllowDelete="True"
		AllowInsert="True"
		AllowUpdate="True"
		SaveMode="Immediate"
		PreFetchRowCount="False"
		>
		<ParameterizedWhereClause><![CDATA[ ]]></ParameterizedWhereClause>
		<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
		<OrderByClause><![CDATA[ ]]></OrderByClause>
		<RSAttributesMeta>
			<DefaultAttributes>
				<RSDefaultAttribute ID="1" Name="Version" />
				<RSDefaultAttribute ID="2" Name="Comments" />
			</DefaultAttributes>
			<ScalerAttributes>
				<RSAttribute Name="Version" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Comments" Displayed="True" UnPlaced="False" />
			</ScalerAttributes>
			<GridAttributes>
				<RSAttribute Name="Version" Displayed="True" UnPlaced="False" />
				<RSAttribute Name="Comments" Displayed="True" UnPlaced="False" />
			</GridAttributes>
		</RSAttributesMeta>
		<ArchetypeExtendedProperties>
			<Property
				Name="AltRowColor"
				Value="#EFEFEF"
			/>
			<Property
				Name="Caption"
				Value=""
			/>
			<Property
				Name="Comments"
				Value=""
			/>
			<Property
				Name="CommentsTrailing"
				Value="&lt;br&gt;"
			/>
			<Property
				Name="Cond0HideRecSrc"
				Value=""
			/>
			<Property
				Name="Cond1"
				Value=""
			/>
			<Property
				Name="Cond1Actions"
				Value=""
			/>
			<Property
				Name="Cond2"
				Value=""
			/>
			<Property
				Name="Cond2Actions"
				Value=""
			/>
			<Property
				Name="Cond3"
				Value=""
			/>
			<Property
				Name="Cond3Actions"
				Value=""
			/>
			<Property
				Name="Cond4"
				Value=""
			/>
			<Property
				Name="Cond4Actions"
				Value=""
			/>
			<Property
				Name="Cond5"
				Value=""
			/>
			<Property
				Name="Cond5Actions"
				Value=""
			/>
			<Property
				Name="ConfirmDeleteMsg"
				Value="Delete record?"
			/>
			<Property
				Name="NoDataMessage"
				Value="&lt;br&gt;&lt;center&gt;&lt;b&gt;No records found!&lt;/b&gt;&lt;/center&gt;&lt;br&gt;"
			/>
			<Property
				Name="ShowHeader"
				Value="true"
			/>
			<Property
				Name="ShowRowCount"
				Value="true"
			/>
			<Property
				Name="ShowRowSelector"
				Value="true"
			/>
			<Property
				Name="SortableHeader"
				Value="true"
			/>
			<Property
				Name="TabCaption"
				Value=""
			/>
			<Property
				Name="TabGenerated"
				Value="true"
			/>
			<Property
				Name="TabImageHeight"
				Value=""
			/>
			<Property
				Name="TabImageOff"
				Value=""
			/>
			<Property
				Name="TabImageOn"
				Value=""
			/>
			<Property
				Name="TabImageWidth"
				Value=""
			/>
			<Property
				Name="UsePopupPicks"
				Value="true"
			/>
		</ArchetypeExtendedProperties>
		<Transition
			FormTransNum="1"
			Prefix="T2"
			TargetFormName="pRepository"
			IsTargetInitialQueryMode="False"
			IsTargetInitialAddMode="False"
			IsVisibleAppline="True"
			IsAddedAfterGen="False"
			FormTransCaption="Repository"
			ClassName="PageNavigation"
			TargetFramesetPage=""
			TargetFrame=""
			FrameNameInFramesetPage=""
			RSID="2"
			BusinessObject="Repository"
			Relationship="Version(ReposVersion)-Repositories(Repository)"
			RelnIsFromParent="True"
			>
			<OrderByClause><![CDATA[ ]]></OrderByClause>
			<ParameterizedWhereClause><![CDATA[ [RepositoryVersion] = [?Version]]]></ParameterizedWhereClause>
			<AdditionalWhereClause><![CDATA[ ]]></AdditionalWhereClause>
		</Transition>
	</RecordSource>
</Form>
