=== tylerm007/MetaRepos/Source/ClientApps/HTMLApps/HTML_ReposMaint.app/Application.dtd
<!ELEMENT Application ( ServerLocation | Description | ApplicationArchetypesFolder | Forms |  References | SourceFiles )*>
<!ATTLIST Application 
	SurrId CDATA #IMPLIED
	ZoomFactor CDATA #IMPLIED
	TargetLanguage (HTML|Java) #REQUIRED
	DefaultLogonUserId CDATA #IMPLIED
	ExecutionEnvironment (Applet|Browser|Application)  #IMPLIED
	AppletHeight CDATA #IMPLIED 
	AppletWidth CDATA #IMPLIED 
	ClassId CDATA  #IMPLIED
	CabVersion CDATA  #IMPLIED
	SuppressDefaultLoginScreen (True|False)  #IMPLIED
	InitialFramesetPage CDATA #IMPLIED
	StartupPageFrameName CDATA #IMPLIED
	InitialFrameNameForStartupTrans CDATA #IMPLIED
	AppRepositoryVersion CDATA #IMPLIED
	DeploySecurityInfo (True | False) #IMPLIED
	DTDVersion CDATA #REQUIRED
	isMDIApp (True|False) #IMPLIED
>

<!ELEMENT Forms (Form)*>
<!ELEMENT References (Reference)*>
<!ELEMENT SourceFiles (SourceFile)*>

<!ELEMENT ServerLocation (#PCDATA )>
<!ELEMENT Description (#PCDATA )>
<!ELEMENT ApplicationArchetypesFolder (#PCDATA )>
<!ELEMENT Form (#PCDATA )>

<!ELEMENT Reference (FileName)*>
<!ATTLIST Reference 
	IsRemote (True|False) #REQUIRED
	Type (VersataFoundationClasses|VersataVLSClasses|JDKClasses|JavaBeans|CORBAObjects|COMWrapperObjects|JavaClasses|CommonClientandServerClasses|
	ClientClasses|ServerClasses|ORBClasses|JavaInterfaceFiles|SwingClasses|GennedComponentInterface|GennedEnterpriseBean|EnterpriseJavaBeans) #REQUIRED
>
<!ELEMENT FileName (#PCDATA)>
<!ELEMENT Path (#PCDATA)>

<!ELEMENT SourceFile (FileName | Path | ClassPath)*>
<!ATTLIST SourceFile
	PackageName CDATA #IMPLIED
>
<!ELEMENT ClassPath (#PCDATA)>

=== tylerm007/MetaRepos/Source/ClientApps/HTMLApps/HTML_ReposMaint.app/HTML_ReposMaint.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Application SYSTEM "Application.dtd">
<Application
	SurrId="0429878456.Tyler.0010"
	ZoomFactor="3"
	TargetLanguage="HTML"
	DefaultLogonUserId="sa"
	ExecutionEnvironment="Browser"
	AppletHeight="575"
	AppletWidth="725"
	ClassId="0526E823-DF30-4AA2-BA9A-C705B0E41B00"
	SuppressDefaultLoginScreen="False"
	InitialFramesetPage="FramesetPage"
	StartupPageFrameName="Startup"
	InitialFrameNameForStartupTrans="Display"
	AppRepositoryVersion="05.05.15"
	DeploySecurityInfo="False"
	DTDVersion="05.05.12"
	>
	<ServerLocation><![CDATA[<localVLSServer>]]></ServerLocation>
	<ApplicationArchetypesFolder><![CDATA[PDXSystemHTMLArchetypes]]></ApplicationArchetypesFolder>
	<!-- APPLICATION FORMS -->
	<Forms>
		<Form>StartupPage</Form>
		<Form>pReposName_Grid</Form>
		<Form>pReposVersion_Grid</Form>
		<Form>pRepository</Form>
		<Form>pDataObject_Grid</Form>
		<Form>pDataObject</Form>
		<Form>pAttribute_Grid</Form>
		<Form>pAttribute</Form>
		<Form>pRelationship_Grid</Form>
		<Form>FramesetPage</Form>
		<Form>pQueryObject_Grid</Form>
		<Form>pQueryObject</Form>
		<Form>pAction_Grid</Form>
		<Form>pAction</Form>
		<Form>pConstraint_Grid</Form>
		<Form>pConstraint</Form>
		<Form>pApplication_Grid</Form>
		<Form>pApplication</Form>
		<Form>pForm_Grid</Form>
		<Form>pRecordSource_Grid</Form>
		<Form>pRSAttribute_Grid</Form>
		<Form>pValidation</Form>
		<Form>pDerivation</Form>
		<Form>pIndexDO_Grid</Form>
		<Form>pIndexAttr_Grid</Form>
		<Form>pMethod_Grid</Form>
		<Form>pGroups_Grid</Form>
		<Form>pRelationshipRole_Grid</Form>
	</Forms>
	<SourceFiles>
	</SourceFiles>
</Application>

=== tylerm007/MetaRepos/Source/ClientApps/HTMLApps/Project1.app/Project1.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Application SYSTEM "Application.dtd">
<Application
	SurrId="0413978431.tband.0020"
	ZoomFactor="2"
	TargetLanguage="HTML"
	DefaultLogonUserId="eop"
	ExecutionEnvironment="Browser"
	AppletHeight="575"
	AppletWidth="725"
	ClassId="9475D7C9-3DAC-4A23-856B-46436C2792F2"
	SuppressDefaultLoginScreen="False"
	InitialFramesetPage="FramesetPage"
	StartupPageFrameName="Startup"
	InitialFrameNameForStartupTrans="Display"
	AppRepositoryVersion="05.05.15"
	DeploySecurityInfo="False"
	DTDVersion="05.05.12"
	>
	<ServerLocation><![CDATA[<localVLSServer>]]></ServerLocation>
	<Description><![CDATA[tband application 1]]></Description>
	<ApplicationArchetypesFolder><![CDATA[..\..\..\..\Versata_55\Pdx\PDXSystemHTMLArchetypes]]></ApplicationArchetypesFolder>
	<!-- APPLICATION FORMS -->
	<Forms>
		<Form>StartupPage</Form>
		<Form>pReposVersion</Form>
		<Form>pDataObject_Grid</Form>
		<Form>pAttribute_Grid</Form>
		<Form>pAction_Grid</Form>
		<Form>pValidation_Grid</Form>
		<Form>pDerivation_Grid</Form>
		<Form>pConstraint_Grid</Form>
		<Form>pDataObject_Jn_Reln_Grid</Form>
		<Form>pRelationship_Grid</Form>
		<Form>pRelationship_Grid11</Form>
		<Form>pDataObject</Form>
		<Form>FramesetPage</Form>
		<Form>pIndexDO_Grid</Form>
		<Form>pIndexAttr_Grid</Form>
		<Form>pAttribute</Form>
		<Form>pRelationship</Form>
		<Form>pAttribute18_Grid</Form>
		<Form>pQry_AttrCount_Grid</Form>
		<Form>pQry_AttrFormula_Grid</Form>
		<Form>pQry_AttrParentRepl_Grid</Form>
		<Form>pQry_AttrSum_Grid</Form>
		<Form>pReposDiff</Form>
		<Form>pApplication</Form>
		<Form>pForm_Grid</Form>
		<Form>pRecordSource</Form>
		<Form>pQueryObject_Grid</Form>
		<Form>pQueryDataObject_Grid</Form>
		<Form>pQueryJoinDataObject_Grid</Form>
		<Form>pRelationshipRole_Grid</Form>
	</Forms>
	<SourceFiles>
	</SourceFiles>
</Application>

=== tylerm007/MetaRepos/Source/ClientApps/JavaApps/ObjectDiff.app/ObjectDiff.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Application SYSTEM "Application.dtd">
<Application
	SurrId="0445211779.Tyler.0005"
	TargetLanguage="Java"
	DefaultLogonUserId="sa"
	ExecutionEnvironment="Applet"
	AppletHeight="575"
	AppletWidth="725"
	ClassId="FB6F3AB9-AA71-4945-845D-36EE54EE384C"
	SuppressDefaultLoginScreen="False"
	InitialFramesetPage=""
	StartupPageFrameName=""
	InitialFrameNameForStartupTrans=""
	AppRepositoryVersion="05.05.15"
	isMDIApp="False"
	DeploySecurityInfo="False"
	DTDVersion="05.05.12"
	>
	<ServerLocation><![CDATA[<localVLSServer>]]></ServerLocation>
	<!-- APPLICATION FORMS -->
	<Forms>
		<Form>StartupForm</Form>
		<Form>fReposDiff</Form>
		<Form>fReposDiff2DataObject</Form>
		<Form>fQueryDiff</Form>
		<Form>fAppDiff</Form>
		<Form>fMethodDiff</Form>
		<Form>fFormDiff</Form>
	</Forms>
	<SourceFiles>
	</SourceFiles>
</Application>

=== tylerm007/MetaRepos/Source/ClientApps/JavaApps/JavaSample.app/JavaSample.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Application SYSTEM "Application.dtd">
<Application
	SurrId="0423874075.Tyler.0002"
	ZoomFactor="3"
	TargetLanguage="Java"
	DefaultLogonUserId="sa"
	ExecutionEnvironment="Application"
	AppletHeight="575"
	AppletWidth="725"
	ClassId="0F4295BF-19E7-4255-8B33-79E052EDDAFA"
	SuppressDefaultLoginScreen="False"
	InitialFramesetPage=""
	StartupPageFrameName=""
	InitialFrameNameForStartupTrans=""
	AppRepositoryVersion="05.05.15"
	isMDIApp="False"
	DeploySecurityInfo="False"
	DTDVersion="05.05.12"
	>
	<ServerLocation><![CDATA[<localVLSServer>]]></ServerLocation>
	<ApplicationArchetypesFolder><![CDATA[C:\Versata_55\Samples\SampDB1\Source\ClientApps\JavaApps\CoolBlueArchetypes]]></ApplicationArchetypesFolder>
	<!-- APPLICATION FORMS -->
	<Forms>
		<Form>StartupForm</Form>
		<Form>fRepository</Form>
		<Form>fAttribute_Grid</Form>
		<Form>fForm_Grid</Form>
		<Form>fQry_AttrCount_Grid</Form>
		<Form>fQry_AttrFormula_Grid</Form>
		<Form>fQry_AttrParentRepl_Grid</Form>
		<Form>fQry_AttrSum_Grid</Form>
		<Form>fReposDiff</Form>
		<Form>fRecordSource_Grid</Form>
		<Form>fOtherFile_Grid</Form>
		<Form>fRSAttribute_Grid</Form>
		<Form>fQueryDataObject_Grid</Form>
		<Form>fMethod_Grid</Form>
		<Form>fReposName</Form>
		<Form>fReposGroups</Form>
		<Form>fRelationshipRole_Grid</Form>
		<Form>fRelationship</Form>
		<Form>fTransition_Grid</Form>
		<Form>fQueryAttr_Grid</Form>
	</Forms>
	<SourceFiles>
		<SourceFile
			PackageName=""
			>
			<FileName><![CDATA[JavaSample.HTML]]></FileName>
			<Path><![CDATA[]]></Path>
		</SourceFile>
	</SourceFiles>
</Application>
