=== tylerm007/MetaRepos/Source/VLS/DataObject.dtd
<!ELEMENT DataObject ( ExtendedProperties | HiddenProperties | Attributes | Constraints | Actions | Indexes | PluralCaption| SingularCaption| Description| Comments | CodedValuesList | VLSDeployment | AttributeGroupInstances )* >
<!ATTLIST DataObject
	XdaConnector CDATA #IMPLIED
	UseQuotedIdentifiers (True|False) #IMPLIED
	CodedValuesList (True|False) #IMPLIED
	SurrId CDATA #IMPLIED
      	LockMode (NoOptimisticLocking|ChangedAttributes|AllApplicableAttributes) #IMPLIED
	SuperClass CDATA #IMPLIED
      	ImageReference CDATA #IMPLIED
      	IsRemoteAccessible (True|False) #IMPLIED
	DTDVersion CDATA #REQUIRED
>

<!ELEMENT AttributeGroupInstances (AttributeGroupInstance)* >
<!ELEMENT OverriddenAttributes (Override)* >
<!ELEMENT Attributes (Attribute)* >
<!ELEMENT Constraints (Constraint)* >
<!ELEMENT Actions (Action)* >
<!ELEMENT Indexes (Index)* >
<!ELEMENT PluralCaption (#PCDATA )>
<!ELEMENT SingularCaption (#PCDATA )>
<!ELEMENT Description (#PCDATA )>
<!ELEMENT Comments (#PCDATA )>
<!ELEMENT HiddenProperties (Property )* >
<!ELEMENT ExtendedProperties (Property )* >
<!ELEMENT Property EMPTY >
<!ATTLIST Property
	Name CDATA #REQUIRED
	Value CDATA #REQUIRED
>
<!ELEMENT Override EMPTY >
<!ATTLIST Override 
	Name CDATA #REQUIRED
>
<!ELEMENT AttributeGroupInstance EMPTY>
<!ATTLIST AttributeGroupInstance
	Name CDATA #REQUIRED
	AttributeGroupTemplate CDATA #REQUIRED
	InheritGrouping (True|False) #IMPLIED
	InheritOrder (True|False) #IMPLIED
	Prefix CDATA #IMPLIED
>
<!ELEMENT CodedValuesList EMPTY>
<!ATTLIST CodedValuesList
	DisplayAttribute CDATA #IMPLIED
	StoredAttribute CDATA #IMPLIED
>

<!ELEMENT VLSDeployment EMPTY>
<!ATTLIST VLSDeployment
	DeploySecurityInfo (True | False) #IMPLIED
>

<!ELEMENT Attribute (DataType | ServerDataType | Derivation | Validation | ExtendedProperties | HiddenProperties | Caption | MicroHelp | Description | Comments | Format| OverriddenAttributes)* >
<!ATTLIST Attribute 
	Name CDATA #REQUIRED
	Persistent (True|False) #IMPLIED 
	ValueRequired (True|False) #IMPLIED
	ArchetypeName CDATA #IMPLIED
	LayoutByDefault (True|False) #IMPLIED
      PreventUserUpdates (True|False) #IMPLIED
	InstanceOf CDATA #IMPLIED
>

<!ELEMENT DataType EMPTY>
<!ATTLIST DataType
	DataType (Char|VarChar|Memo|Byte|AutoNumber|Integer|Long|Double|Single|Decimal|Float|Date|Time|DateTime|Boolean|Currency|LongBinary) #IMPLIED 
	Size CDATA #IMPLIED
	Precision CDATA #IMPLIED
	Scale CDATA #IMPLIED

>

<!ELEMENT ServerDataType EMPTY>
<!ATTLIST ServerDataType
	Type CDATA #IMPLIED
	Size CDATA #IMPLIED
	ServerOfOrigin (Oracle7|SQLServer|Sybase11|Informix|DB2UDB|BLANK) #IMPLIED
>
<!ELEMENT Derivation (DefaultValue | Formula | QualificationExpression )*>
<!ATTLIST Derivation
	DerivationType (None|Sum|Count|ParentReplicate|Formula|Default) #IMPLIED 
	SourceDataObject CDATA #IMPLIED
     	ParentReplicateIsMaintained (True|False) #IMPLIED
     	SourceAttribute CDATA #IMPLIED
>
<!ELEMENT Validation (Condition | ErrorMessage )*>
<!ATTLIST Validation
	ValidationType (Condition|CodedValuesList) #IMPLIED
	CodedValuesList CDATA #IMPLIED
>

<!ELEMENT Caption (#PCDATA )>
<!ELEMENT MicroHelp (#PCDATA )>
<!ELEMENT DefaultValue (#PCDATA )>
<!ELEMENT Formula (#PCDATA )>
<!ELEMENT QualificationExpression (#PCDATA )>
<!ELEMENT Format (#PCDATA )>


<!ELEMENT Constraint (  Condition | ErrorMessage )* >
<!ATTLIST Constraint 
	Name CDATA #REQUIRED
	ConditionType (RejectWhen|AcceptWhen) #REQUIRED
	ErrorAttribute CDATA #IMPLIED
>


<!ELEMENT Condition (#PCDATA )>
<!ELEMENT ErrorMessage (#PCDATA )>

<!ELEMENT Action ( ActionToPerform |Condition|Description )* >
<!ATTLIST Action 

	Name CDATA #REQUIRED
>

<!ELEMENT ActionToPerform (#PCDATA )>

 
<!ELEMENT Index ( Index_Attribute )* >
<!ATTLIST Index 
	IgnoreNulls (True|False) #REQUIRED
	Name CDATA #REQUIRED
	Primary (True|False) #REQUIRED
	Unique (True|False) #REQUIRED
	AttributeGroupInstance CDATA #IMPLIED
>
<!ELEMENT Index_Attribute EMPTY >
<!ATTLIST Index_Attribute
	Name CDATA #REQUIRED
	Descending (True|False) #IMPLIED
>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/Organization/QueryAttr.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	DTDVersion="05.05.12"
	SurrId="0443013144.Tyler.0000"
	CodedValuesList="False"
	ImageReference=" "
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	XdaConnector="SQL"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	>
	<Attributes>
		<Attribute
			Name="RepositoryName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="QueryObjectName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="DataObjectName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="AttrName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Alias"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="AggregationType"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Persistent"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Boolean"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[true]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="PK_QRYATTR"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="RepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="DataObjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="QueryObjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="AttrName"
				Descending="False"
			/>
			<Index_Attribute
				Name="Alias"
				Descending="False"
			/>
		</Index>
	</Indexes>
	<SingularCaption><![CDATA[*]]></SingularCaption>
	<PluralCaption><![CDATA[*]]></PluralCaption>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/Organization/Object_JN_Group.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	SurrId="0416912984.tband.0015"
	CodedValuesList="False"
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	ImageReference=" "
	XdaConnector="SQL"
	DTDVersion="05.05.12"
	>
	<CodedValuesList
		DisplayAttribute=" "
		StoredAttribute=" "
	/>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<SingularCaption><![CDATA[*]]> </SingularCaption>
	<PluralCaption><![CDATA[*]]> </PluralCaption>
	<Description><![CDATA[ This allows multiple objects (by ObjectType) to be joined to a specific group.]]> </Description>
	<Comments><![CDATA[ ]]> </Comments>
	<Attributes>
		<Attribute
			Name="GroupName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="100"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="RepositoryName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="ObjectName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
		</Attribute>
		<Attribute
			Name="ObjectType"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="12"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="CodedValuesList"
				CodedValuesList="Valid_ObjectType"
			/>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="DataObjectGroupPkey"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="RepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="GroupName"
				Descending="False"
			/>
			<Index_Attribute
				Name="ObjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="ObjectType"
				Descending="False"
			/>
		</Index>
	</Indexes>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/RuleObjects/Validation.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	SurrId="0413978431.tband.0013"
	CodedValuesList="False"
	ImageReference=" "
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	XdaConnector="SQL"
	DTDVersion="05.05.12"
	>
	<CodedValuesList
		DisplayAttribute=" "
		StoredAttribute=" "
	/>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<SingularCaption><![CDATA[*]]> </SingularCaption>
	<PluralCaption><![CDATA[*]]> </PluralCaption>
	<Description><![CDATA[ These are coded value lists - (used to display drop down lists of valid values)]]> </Description>
	<Comments><![CDATA[ In the future - I would like to include the values of the CVS files as XML code.]]> </Comments>
	<Attributes>
		<Attribute
			Name="RepositoryName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Rpository Name]]></Caption>
		</Attribute>
		<Attribute
			Name="DataObjectName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Data Object]]></Caption>
		</Attribute>
		<Attribute
			Name="AttrName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Attribute Name]]></Caption>
		</Attribute>
		<Attribute
			Name="ValidationType"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Validation Type]]></Caption>
		</Attribute>
		<Attribute
			Name="Description"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Memo"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="CodedValueList"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Coded Value List]]></Caption>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="ValidationPkey"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="RepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="DataObjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="AttrName"
				Descending="False"
			/>
			<Index_Attribute
				Name="ValidationType"
				Descending="False"
			/>
		</Index>
	</Indexes>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/Organization/DataObject_Jn_Reln.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	SurrId="0413978431.tband.0015"
	CodedValuesList="False"
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	ImageReference=" "
	XdaConnector="SQL"
	DTDVersion="05.05.12"
	>
	<CodedValuesList
		DisplayAttribute=" "
		StoredAttribute=" "
	/>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<SingularCaption><![CDATA[*]]> </SingularCaption>
	<PluralCaption><![CDATA[*]]> </PluralCaption>
	<Description><![CDATA[ This allows a many to many relationship between dataobjects, relationships, and roles.]]> </Description>
	<Comments><![CDATA[ ]]> </Comments>
	<Attributes>
		<Attribute
			Name="RepositoryName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="DataObjectName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="RelationshipName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="150"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="isParentRole"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Boolean"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[true]]> </DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[IsParent  Role?]]> </Caption>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="DOJNRELNPKEY"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="RepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="DataObjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="RelationshipName"
				Descending="False"
			/>
			<Index_Attribute
				Name="isParentRole"
				Descending="False"
			/>
		</Index>
	</Indexes>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/WorkFlow/Template.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	DTDVersion="05.05.12"
	SurrId="0444567293.Tyler.0000"
	CodedValuesList="False"
	ImageReference=" "
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	XdaConnector="SQL"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	>
	<Attributes>
		<Attribute
			Name="TemplateName"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="PK_Template"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="TemplateName"
				Descending="False"
			/>
		</Index>
	</Indexes>
	<SingularCaption><![CDATA[*]]></SingularCaption>
	<PluralCaption><![CDATA[*]]></PluralCaption>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/Root_Objects/Relationship.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	SurrId="04405093650000"
	CodedValuesList="False"
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	ImageReference=" "
	XdaConnector="SQL"
	DTDVersion="05.05.12"
	>
	<CodedValuesList
		DisplayAttribute=" "
		StoredAttribute=" "
	/>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<SingularCaption><![CDATA[*]]> </SingularCaption>
	<PluralCaption><![CDATA[*]]> </PluralCaption>
	<Description><![CDATA[ A relationship (association) allows the navigation between 2 dataobjects (role-players).  These roles are usually defined by cardinality with a starting point (the parent role) and the end point (the child role).]]> </Description>
	<Comments><![CDATA[ For Most single relationships between parent and child - the values on this object will be correct.  If there are more than 1 role player between parent and child - these will be found in the RelationshipRole object (with the correct values)]]> </Comments>
	<Attributes>
		<Attribute
			Name="RepositoryName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Repository Name]]></Caption>
		</Attribute>
		<Attribute
			Name="RelationshipName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="150"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Relationship Name]]></Caption>
		</Attribute>
		<Attribute
			Name="ParentDOName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Parent Data Object]]></Caption>
			<Description><![CDATA[IFF there is only a single role this value is valid , else navigate to RelationshipRole for details]]></Description>
		</Attribute>
		<Attribute
			Name="ParentRoleName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Parent Role Name]]></Caption>
			<Description><![CDATA[IFF there is only a single role this value is valid , else navigate to RelationshipRole for details]]></Description>
		</Attribute>
		<Attribute
			Name="ChildDOName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Child Data Object]]></Caption>
			<Description><![CDATA[IFF there is only a single role this value is valid , else navigate to RelationshipRole for details]]></Description>
		</Attribute>
		<Attribute
			Name="ChildRoleName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Child Role Name]]></Caption>
			<Description><![CDATA[IFF there is only a single role this value is valid , else navigate to RelationshipRole for details]]></Description>
		</Attribute>
		<Attribute
			Name="isEnforce"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Boolean"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[true]]> </DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[Is Relationship Enforced?]]></Caption>
			<Description><![CDATA[IFF there is only a single role this value is valid , else navigate to RelationshipRole for details]]></Description>
		</Attribute>
		<Attribute
			Name="ParentAttribute"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Parent Attribute]]></Caption>
			<Description><![CDATA[IFF there is only a single role this value is valid , else navigate to RelationshipRole for details]]></Description>
		</Attribute>
		<Attribute
			Name="ChildAttribute"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Child Attribute]]></Caption>
			<Description><![CDATA[IFF there is only a single role this value is valid , else navigate to RelationshipRole for details]]></Description>
		</Attribute>
		<Attribute
			Name="RolePlayer_CNT"
			PreventUserUpdates="True"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				SourceDataObject="RelationshipRole(RelationshipRole)"
				DerivationType="Count"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Description><![CDATA[This tells us if there is more than 1 role player - if so - then use the RelationshipRole for actual metadata information.]]></Description>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="RelnPkey"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="RepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="RelationshipName"
				Descending="False"
			/>
		</Index>
		<Index
			Name="KeyRelToRelRole"
			Primary="False"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="RepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="RelationshipName"
				Descending="False"
			/>
			<Index_Attribute
				Name="ParentDOName"
				Descending="False"
			/>
			<Index_Attribute
				Name="ChildDOName"
				Descending="False"
			/>
		</Index>
	</Indexes>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/CDDMap/AttrObjectMapper.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	SurrId="04445674550040"
	CodedValuesList="False"
	ImageReference=" "
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	XdaConnector="SQL"
	DTDVersion="05.05.12"
	>
	<CodedValuesList
		DisplayAttribute=" "
		StoredAttribute=" "
	/>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<SingularCaption><![CDATA[Attribute Mapper]]> </SingularCaption>
	<PluralCaption><![CDATA[Attribute Mapper]]> </PluralCaption>
	<Description><![CDATA[ This project can have many mappings between 2 or more DataObjects from multiple Repository projects - each Attribute pair represents a possible transformation to test between 2 systems.]]> </Description>
	<Comments><![CDATA[ DataType Checks - are the datatypes compatible?
Multiple Source Columns mapped to same Target?  [Handle in GUI]
Multiple Targets mapped to single Source? [Handle in GUI]]]> </Comments>
	<Attributes>
		<Attribute
			Name="ProjectName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Project Name]]></Caption>
		</Attribute>
		<Attribute
			Name="SourceRepositoryName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Source Repository Name]]></Caption>
		</Attribute>
		<Attribute
			Name="TargetRepositoryName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Target Repository Name]]></Caption>
		</Attribute>
		<Attribute
			Name="SourceDataObjectName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Source DataObject Name]]></Caption>
		</Attribute>
		<Attribute
			Name="TargetDataObjectName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Target DataObject Name]]></Caption>
		</Attribute>
		<Attribute
			Name="SourceAttrName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Source Attr Name]]></Caption>
		</Attribute>
		<Attribute
			Name="TargetAttrName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Target  Attr  Name]]></Caption>
		</Attribute>
		<Attribute
			Name="TransformDesc"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="250"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[Transform Requirment]]></Caption>
		</Attribute>
		<Attribute
			Name="TransformRule"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="15"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA['NONE']]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="CodedValuesList"
				CodedValuesList="Valid_TransformRule"
			/>
		</Attribute>
		<Attribute
			Name="SourceAttrDatatype"
			PreventUserUpdates="True"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				SourceDataObject="SourceAttribute(Attribute)"
				SourceAttribute="SQLDataType"
				ParentReplicateIsMaintained="False"
				DerivationType="ParentReplicate"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="TargetAttrDatatype"
			PreventUserUpdates="True"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				SourceDataObject="TargetAttribute(Attribute)"
				SourceAttribute="SQLDataType"
				ParentReplicateIsMaintained="False"
				DerivationType="ParentReplicate"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="PkeyATTRMapper"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="ProjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="SourceRepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="TargetRepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="SourceDataObjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="TargetDataObjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="SourceAttrName"
				Descending="False"
			/>
			<Index_Attribute
				Name="TargetAttrName"
				Descending="False"
			/>
		</Index>
	</Indexes>
</DataObject>
