=== tylerm007/MetaRepos/Source/VLS/DataObject.dtd
<!ELEMENT DataObject ( ExtendedProperties | HiddenProperties | Attributes | Constraints | Actions | Indexes | PluralCaption| SingularCaption| Description| Comments | CodedValuesList | VLSDeployment | AttributeGroupInstances )* >
<!ATTLIST DataObject
	XdaConnector CDATA #IMPLIED
	UseQuotedIdentifiers (True|False) #IMPLIED
	CodedValuesList (True|False) #IMPLIED
	SurrId CDATA #IMPLIED
      	LockMode (NoOptimisticLocking|ChangedAttributes|AllApplicableAttributes) #IMPLIED
	SuperClass CDATA #IMPLIED
      	ImageReference CDATA #IMPLIED
      	IsRemoteAccessible (True|False) #IMPLIED
	DTDVersion CDATA #REQUIRED
>

<!ELEMENT AttributeGroupInstances (AttributeGroupInstance)* >
<!ELEMENT OverriddenAttributes (Override)* >
<!ELEMENT Attributes (Attribute)* >
<!ELEMENT Constraints (Constraint)* >
<!ELEMENT Actions (Action)* >
<!ELEMENT Indexes (Index)* >
<!ELEMENT PluralCaption (#PCDATA )>
<!ELEMENT SingularCaption (#PCDATA )>
<!ELEMENT Description (#PCDATA )>
<!ELEMENT Comments (#PCDATA )>
<!ELEMENT HiddenProperties (Property )* >
<!ELEMENT ExtendedProperties (Property )* >
<!ELEMENT Property EMPTY >
<!ATTLIST Property
	Name CDATA #REQUIRED
	Value CDATA #REQUIRED
>
<!ELEMENT Override EMPTY >
<!ATTLIST Override 
	Name CDATA #REQUIRED
>
<!ELEMENT AttributeGroupInstance EMPTY>
<!ATTLIST AttributeGroupInstance
	Name CDATA #REQUIRED
	AttributeGroupTemplate CDATA #REQUIRED
	InheritGrouping (True|False) #IMPLIED
	InheritOrder (True|False) #IMPLIED
	Prefix CDATA #IMPLIED
>
<!ELEMENT CodedValuesList EMPTY>
<!ATTLIST CodedValuesList
	DisplayAttribute CDATA #IMPLIED
	StoredAttribute CDATA #IMPLIED
>

<!ELEMENT VLSDeployment EMPTY>
<!ATTLIST VLSDeployment
	DeploySecurityInfo (True | False) #IMPLIED
>

<!ELEMENT Attribute (DataType | ServerDataType | Derivation | Validation | ExtendedProperties | HiddenProperties | Caption | MicroHelp | Description | Comments | Format| OverriddenAttributes)* >
<!ATTLIST Attribute 
	Name CDATA #REQUIRED
	Persistent (True|False) #IMPLIED 
	ValueRequired (True|False) #IMPLIED
	ArchetypeName CDATA #IMPLIED
	LayoutByDefault (True|False) #IMPLIED
      PreventUserUpdates (True|False) #IMPLIED
	InstanceOf CDATA #IMPLIED
>

<!ELEMENT DataType EMPTY>
<!ATTLIST DataType
	DataType (Char|VarChar|Memo|Byte|AutoNumber|Integer|Long|Double|Single|Decimal|Float|Date|Time|DateTime|Boolean|Currency|LongBinary) #IMPLIED 
	Size CDATA #IMPLIED
	Precision CDATA #IMPLIED
	Scale CDATA #IMPLIED

>

<!ELEMENT ServerDataType EMPTY>
<!ATTLIST ServerDataType
	Type CDATA #IMPLIED
	Size CDATA #IMPLIED
	ServerOfOrigin (Oracle7|SQLServer|Sybase11|Informix|DB2UDB|BLANK) #IMPLIED
>
<!ELEMENT Derivation (DefaultValue | Formula | QualificationExpression )*>
<!ATTLIST Derivation
	DerivationType (None|Sum|Count|ParentReplicate|Formula|Default) #IMPLIED 
	SourceDataObject CDATA #IMPLIED
     	ParentReplicateIsMaintained (True|False) #IMPLIED
     	SourceAttribute CDATA #IMPLIED
>
<!ELEMENT Validation (Condition | ErrorMessage )*>
<!ATTLIST Validation
	ValidationType (Condition|CodedValuesList) #IMPLIED
	CodedValuesList CDATA #IMPLIED
>

<!ELEMENT Caption (#PCDATA )>
<!ELEMENT MicroHelp (#PCDATA )>
<!ELEMENT DefaultValue (#PCDATA )>
<!ELEMENT Formula (#PCDATA )>
<!ELEMENT QualificationExpression (#PCDATA )>
<!ELEMENT Format (#PCDATA )>


<!ELEMENT Constraint (  Condition | ErrorMessage )* >
<!ATTLIST Constraint 
	Name CDATA #REQUIRED
	ConditionType (RejectWhen|AcceptWhen) #REQUIRED
	ErrorAttribute CDATA #IMPLIED
>


<!ELEMENT Condition (#PCDATA )>
<!ELEMENT ErrorMessage (#PCDATA )>

<!ELEMENT Action ( ActionToPerform |Condition|Description )* >
<!ATTLIST Action 

	Name CDATA #REQUIRED
>

<!ELEMENT ActionToPerform (#PCDATA )>

 
<!ELEMENT Index ( Index_Attribute )* >
<!ATTLIST Index 
	IgnoreNulls (True|False) #REQUIRED
	Name CDATA #REQUIRED
	Primary (True|False) #REQUIRED
	Unique (True|False) #REQUIRED
	AttributeGroupInstance CDATA #IMPLIED
>
<!ELEMENT Index_Attribute EMPTY >
<!ATTLIST Index_Attribute
	Name CDATA #REQUIRED
	Descending (True|False) #IMPLIED
>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/Organization/FormObjectDiff.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	DTDVersion="05.05.12"
	SurrId="04456371760003"
	CodedValuesList="False"
	ImageReference=" "
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	XdaConnector="SQL"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	>
	<Attributes>
		<Attribute
			Name="ReposName1"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="ReposName2"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="AppName1"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="AppName2"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="FormName1"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
		</Attribute>
		<Attribute
			Name="FormName2"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
		</Attribute>
		<Attribute
			Name="ObjectType"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA['HTML_APP']]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="CodedValuesList"
				CodedValuesList="Valid_ObjectType"
			/>
		</Attribute>
		<Attribute
			Name="DiffComment"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="250"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Description><![CDATA[This will say something like Added to Repos2 or Removed from Repos 2 - or modified (each object will have different criteria, e.g #attrs, lines of code, methods, etc.)]]></Description>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Total_1_Line_Cnt"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[0]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Total_2_Line_Cnt"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[0]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Line_Cnt_Diff"
			PreventUserUpdates="True"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Formula"
				>
				<Formula><![CDATA[ Total_1_Line_Cnt  -  Total_2_Line_Cnt ]]></Formula>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Total_1_Method_Cnt"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[0]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Total_2_Method_Cnt"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[0]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="RecordSource1_Cnt"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[0]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="RecordSource2_Cnt"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[0]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Transition1_Cnt"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[0]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Transition2_Cnt"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[0]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Method_Cnt_Diff"
			PreventUserUpdates="True"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Formula"
				>
				<Formula><![CDATA[ Total_1_Method_Cnt  -  Total_2_Method_Cnt ]]></Formula>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="DiffState"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="12"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA['SAME']]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="CodedValuesList"
				CodedValuesList="List_DiffState"
			/>
		</Attribute>
		<Attribute
			Name="RecordSourceCnt_Diff"
			PreventUserUpdates="True"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Formula"
				>
				<Formula><![CDATA[ RecordSource1_Cnt  -  RecordSource2_Cnt ]]></Formula>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="TransitionCnt_Diff"
			PreventUserUpdates="True"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Formula"
				>
				<Formula><![CDATA[ Transition1_Cnt  -  Transition2_Cnt ]]></Formula>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="FormType"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA['HTML']]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="PKObjectDiff"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="ReposName1"
				Descending="False"
			/>
			<Index_Attribute
				Name="AppName1"
				Descending="False"
			/>
			<Index_Attribute
				Name="ReposName2"
				Descending="False"
			/>
			<Index_Attribute
				Name="AppName2"
				Descending="False"
			/>
			<Index_Attribute
				Name="ObjectType"
				Descending="False"
			/>
			<Index_Attribute
				Name="FormName1"
				Descending="False"
			/>
			<Index_Attribute
				Name="FormName2"
				Descending="False"
			/>
			<Index_Attribute
				Name="FormType"
				Descending="False"
			/>
		</Index>
	</Indexes>
	<SingularCaption><![CDATA[Object Difference]]></SingularCaption>
	<PluralCaption><![CDATA[Object Differences]]></PluralCaption>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<CodedValuesList
		StoredAttribute=" "
		DisplayAttribute=" "
	/>
	<Description><![CDATA[ObjectDiff is an internal object created and maintained by Java code.  This holds the difference information between 2 objects (DataObject, Attribute, Query, etc)]]></Description>
	<Comments><![CDATA[ ]]></Comments>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/RuleObjects/RSAttribute.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	SurrId="0416912984.tband.0006"
	CodedValuesList="False"
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	ImageReference=" "
	XdaConnector="SQL"
	DTDVersion="05.05.12"
	>
	<CodedValuesList
		DisplayAttribute=" "
		StoredAttribute=" "
	/>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<SingularCaption><![CDATA[*]]> </SingularCaption>
	<PluralCaption><![CDATA[*]]> </PluralCaption>
	<Description><![CDATA[ These are the attributes defined by this record source that are placed and displayed in an HTML page or Java Form.]]> </Description>
	<Comments><![CDATA[ ]]> </Comments>
	<Attributes>
		<Attribute
			Name="RepositoryName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Repository Name]]></Caption>
		</Attribute>
		<Attribute
			Name="ApplicationName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="100"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Application Name]]></Caption>
		</Attribute>
		<Attribute
			Name="FormName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="100"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Form Name]]></Caption>
		</Attribute>
		<Attribute
			Name="BusinessObject"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Business Object]]></Caption>
		</Attribute>
		<Attribute
			Name="AttrName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[AttributeName]]></Caption>
		</Attribute>
		<Attribute
			Name="isScalar"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Boolean"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[false]]> </DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[Scalar?]]></Caption>
		</Attribute>
		<Attribute
			Name="isPlaced"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Boolean"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[false]]> </DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[UnPlaced?]]></Caption>
		</Attribute>
		<Attribute
			Name="isDisplayed"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Boolean"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[false]]> </DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[Is Displayed?]]></Caption>
		</Attribute>
		<Attribute
			Name="RSID"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[1]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[RecordSource ID]]></Caption>
		</Attribute>
		<Attribute
			Name="ColumnLabel"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="150"
			/>
			<Derivation
				DerivationType="None"
				>
				<DefaultValue><![CDATA[]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="ClassName"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="150"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA['default']]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="ColumnEnabled"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Boolean"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[true]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="RecordSourceAttrPkey"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="RepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="ApplicationName"
				Descending="False"
			/>
			<Index_Attribute
				Name="FormName"
				Descending="False"
			/>
			<Index_Attribute
				Name="BusinessObject"
				Descending="False"
			/>
			<Index_Attribute
				Name="RSID"
				Descending="False"
			/>
			<Index_Attribute
				Name="AttrName"
				Descending="False"
			/>
			<Index_Attribute
				Name="isScalar"
				Descending="False"
			/>
		</Index>
	</Indexes>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/RuleObjects/Constraint.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	SurrId="0413978431.tband.0007"
	CodedValuesList="False"
	ImageReference=" "
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	XdaConnector="SQL"
	DTDVersion="05.05.12"
	>
	<CodedValuesList
		DisplayAttribute=" "
		StoredAttribute=" "
	/>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<SingularCaption><![CDATA[*]]> </SingularCaption>
	<PluralCaption><![CDATA[*]]> </PluralCaption>
	<Description><![CDATA[ Constraints are used by DataObjects to prevent or accept state change.  Rules that test state change are fired at the DataObject level only.]]> </Description>
	<Comments><![CDATA[ ]]> </Comments>
	<Attributes>
		<Attribute
			Name="RepositoryName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="False"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Repository Name]]></Caption>
		</Attribute>
		<Attribute
			Name="DataObjectName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Data Object]]></Caption>
		</Attribute>
		<Attribute
			Name="ConstraintName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Constraint Name]]></Caption>
		</Attribute>
		<Attribute
			Name="ConditionType"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Type]]></Caption>
		</Attribute>
		<Attribute
			Name="Condition"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Memo"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="ErrorMessage"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Memo"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Error Message]]></Caption>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="ConstraintPkey"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="RepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="DataObjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="ConstraintName"
				Descending="False"
			/>
		</Index>
	</Indexes>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/RuleObjects/Action.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	SurrId="0413978431.tband.0005"
	CodedValuesList="False"
	ImageReference=" "
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	XdaConnector="SQL"
	DTDVersion="05.05.12"
	>
	<CodedValuesList
		DisplayAttribute=" "
		StoredAttribute=" "
	/>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<SingularCaption><![CDATA[*]]> </SingularCaption>
	<PluralCaption><![CDATA[*]]> </PluralCaption>
	<Description><![CDATA[ These are the Event Condition Actions - rules that only fire Java Methods when an Event (a business state change) occurs.]]> </Description>
	<Comments><![CDATA[ ]]> </Comments>
	<Attributes>
		<Attribute
			Name="RepositoryName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="False"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Repository Name]]></Caption>
		</Attribute>
		<Attribute
			Name="DataObjectName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Data Object]]></Caption>
		</Attribute>
		<Attribute
			Name="ActionName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Action Name]]></Caption>
		</Attribute>
		<Attribute
			Name="ActionToPerform"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Memo"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Action to Perform]]></Caption>
		</Attribute>
		<Attribute
			Name="Description"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Memo"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Condition"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Memo"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="ActionPkey"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="RepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="DataObjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="ActionName"
				Descending="False"
			/>
		</Index>
	</Indexes>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/Organization/QueryDataObject.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	SurrId="0417538787.tband.0002"
	CodedValuesList="False"
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	ImageReference=" "
	XdaConnector="SQL"
	DTDVersion="05.05.12"
	>
	<CodedValuesList
		DisplayAttribute=" "
		StoredAttribute=" "
	/>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<SingularCaption><![CDATA[*]]> </SingularCaption>
	<PluralCaption><![CDATA[*]]> </PluralCaption>
	<Description><![CDATA[ Each QueryObject will have at least 1 DataObject as a child and be joined to that object via a relationship.]]> </Description>
	<Comments><![CDATA[ ]]> </Comments>
	<Attributes>
		<Attribute
			Name="RepositoryName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="QueryObjectName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="DataObjectName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Alias"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="QueryDataObjPkey"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="RepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="QueryObjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="DataObjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="Alias"
				Descending="False"
			/>
		</Index>
	</Indexes>
</DataObject>
