=== tylerm007/MetaRepos/Source/VLS/DataObject.dtd
<!ELEMENT DataObject ( ExtendedProperties | HiddenProperties | Attributes | Constraints | Actions | Indexes | PluralCaption| SingularCaption| Description| Comments | CodedValuesList | VLSDeployment | AttributeGroupInstances )* >
<!ATTLIST DataObject
	XdaConnector CDATA #IMPLIED
	UseQuotedIdentifiers (True|False) #IMPLIED
	CodedValuesList (True|False) #IMPLIED
	SurrId CDATA #IMPLIED
      	LockMode (NoOptimisticLocking|ChangedAttributes|AllApplicableAttributes) #IMPLIED
	SuperClass CDATA #IMPLIED
      	ImageReference CDATA #IMPLIED
      	IsRemoteAccessible (True|False) #IMPLIED
	DTDVersion CDATA #REQUIRED
>

<!ELEMENT AttributeGroupInstances (AttributeGroupInstance)* >
<!ELEMENT OverriddenAttributes (Override)* >
<!ELEMENT Attributes (Attribute)* >
<!ELEMENT Constraints (Constraint)* >
<!ELEMENT Actions (Action)* >
<!ELEMENT Indexes (Index)* >
<!ELEMENT PluralCaption (#PCDATA )>
<!ELEMENT SingularCaption (#PCDATA )>
<!ELEMENT Description (#PCDATA )>
<!ELEMENT Comments (#PCDATA )>
<!ELEMENT HiddenProperties (Property )* >
<!ELEMENT ExtendedProperties (Property )* >
<!ELEMENT Property EMPTY >
<!ATTLIST Property
	Name CDATA #REQUIRED
	Value CDATA #REQUIRED
>
<!ELEMENT Override EMPTY >
<!ATTLIST Override 
	Name CDATA #REQUIRED
>
<!ELEMENT AttributeGroupInstance EMPTY>
<!ATTLIST AttributeGroupInstance
	Name CDATA #REQUIRED
	AttributeGroupTemplate CDATA #REQUIRED
	InheritGrouping (True|False) #IMPLIED
	InheritOrder (True|False) #IMPLIED
	Prefix CDATA #IMPLIED
>
<!ELEMENT CodedValuesList EMPTY>
<!ATTLIST CodedValuesList
	DisplayAttribute CDATA #IMPLIED
	StoredAttribute CDATA #IMPLIED
>

<!ELEMENT VLSDeployment EMPTY>
<!ATTLIST VLSDeployment
	DeploySecurityInfo (True | False) #IMPLIED
>

<!ELEMENT Attribute (DataType | ServerDataType | Derivation | Validation | ExtendedProperties | HiddenProperties | Caption | MicroHelp | Description | Comments | Format| OverriddenAttributes)* >
<!ATTLIST Attribute 
	Name CDATA #REQUIRED
	Persistent (True|False) #IMPLIED 
	ValueRequired (True|False) #IMPLIED
	ArchetypeName CDATA #IMPLIED
	LayoutByDefault (True|False) #IMPLIED
      PreventUserUpdates (True|False) #IMPLIED
	InstanceOf CDATA #IMPLIED
>

<!ELEMENT DataType EMPTY>
<!ATTLIST DataType
	DataType (Char|VarChar|Memo|Byte|AutoNumber|Integer|Long|Double|Single|Decimal|Float|Date|Time|DateTime|Boolean|Currency|LongBinary) #IMPLIED 
	Size CDATA #IMPLIED
	Precision CDATA #IMPLIED
	Scale CDATA #IMPLIED

>

<!ELEMENT ServerDataType EMPTY>
<!ATTLIST ServerDataType
	Type CDATA #IMPLIED
	Size CDATA #IMPLIED
	ServerOfOrigin (Oracle7|SQLServer|Sybase11|Informix|DB2UDB|BLANK) #IMPLIED
>
<!ELEMENT Derivation (DefaultValue | Formula | QualificationExpression )*>
<!ATTLIST Derivation
	DerivationType (None|Sum|Count|ParentReplicate|Formula|Default) #IMPLIED 
	SourceDataObject CDATA #IMPLIED
     	ParentReplicateIsMaintained (True|False) #IMPLIED
     	SourceAttribute CDATA #IMPLIED
>
<!ELEMENT Validation (Condition | ErrorMessage )*>
<!ATTLIST Validation
	ValidationType (Condition|CodedValuesList) #IMPLIED
	CodedValuesList CDATA #IMPLIED
>

<!ELEMENT Caption (#PCDATA )>
<!ELEMENT MicroHelp (#PCDATA )>
<!ELEMENT DefaultValue (#PCDATA )>
<!ELEMENT Formula (#PCDATA )>
<!ELEMENT QualificationExpression (#PCDATA )>
<!ELEMENT Format (#PCDATA )>


<!ELEMENT Constraint (  Condition | ErrorMessage )* >
<!ATTLIST Constraint 
	Name CDATA #REQUIRED
	ConditionType (RejectWhen|AcceptWhen) #REQUIRED
	ErrorAttribute CDATA #IMPLIED
>


<!ELEMENT Condition (#PCDATA )>
<!ELEMENT ErrorMessage (#PCDATA )>

<!ELEMENT Action ( ActionToPerform |Condition|Description )* >
<!ATTLIST Action 

	Name CDATA #REQUIRED
>

<!ELEMENT ActionToPerform (#PCDATA )>

 
<!ELEMENT Index ( Index_Attribute )* >
<!ATTLIST Index 
	IgnoreNulls (True|False) #REQUIRED
	Name CDATA #REQUIRED
	Primary (True|False) #REQUIRED
	Unique (True|False) #REQUIRED
	AttributeGroupInstance CDATA #IMPLIED
>
<!ELEMENT Index_Attribute EMPTY >
<!ATTLIST Index_Attribute
	Name CDATA #REQUIRED
	Descending (True|False) #IMPLIED
>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/CDDMap/Project.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	DTDVersion="05.05.12"
	SurrId="0444579108.Tyler.0000"
	CodedValuesList="False"
	ImageReference=" "
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	XdaConnector="SQL"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	>
	<Attributes>
		<Attribute
			Name="ProjectName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[CDD Project Name]]></Caption>
		</Attribute>
		<Attribute
			Name="ProjectDescription"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="250"
			/>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="PkeyProject"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="ProjectName"
				Descending="False"
			/>
		</Index>
	</Indexes>
	<SingularCaption><![CDATA[Common Data Dictionary Project]]></SingularCaption>
	<PluralCaption><![CDATA[CDD Projects]]></PluralCaption>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<Description><![CDATA[ Common Data Dictionary Mapping Project]]></Description>
	<Comments><![CDATA[ Mapping must be dependent on specific version of objects (Data and Attributes).  ]]></Comments>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/RuleObjects/IndexDO.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	SurrId="0414404847.tband.0002"
	CodedValuesList="False"
	ImageReference=" "
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	XdaConnector="SQL"
	DTDVersion="05.05.12"
	>
	<CodedValuesList
		DisplayAttribute=" "
		StoredAttribute=" "
	/>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<SingularCaption><![CDATA[*]]> </SingularCaption>
	<PluralCaption><![CDATA[*]]> </PluralCaption>
	<Description><![CDATA[ This is the Index Data Object - used by DBMS to identify primary and foreign keys.]]> </Description>
	<Comments><![CDATA[ ]]> </Comments>
	<Attributes>
		<Attribute
			Name="RepositoryName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Repository Name]]></Caption>
		</Attribute>
		<Attribute
			Name="DataObjectName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Data Object]]></Caption>
		</Attribute>
		<Attribute
			Name="IndexName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Index Name]]></Caption>
		</Attribute>
		<Attribute
			Name="PrimaryIndx"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Boolean"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[false]]> </DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[Is Primary?]]></Caption>
		</Attribute>
		<Attribute
			Name="UniqueIndx"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Boolean"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[false]]> </DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[Is Unique?]]></Caption>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="PKEYIndex"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="RepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="DataObjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="IndexName"
				Descending="False"
			/>
		</Index>
	</Indexes>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/Validation/List_DiffState.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	DTDVersion="05.05.12"
	SurrId="0445211779.Tyler.0006"
	CodedValuesList="True"
	ImageReference=" "
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	XdaConnector="SQL"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	>
	<Attributes>
		<Attribute
			Name="DiffState"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="12"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="DiffDescription"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="PKeyDiffState"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="DiffState"
				Descending="False"
			/>
		</Index>
	</Indexes>
	<SingularCaption><![CDATA[*]]></SingularCaption>
	<PluralCaption><![CDATA[*]]></PluralCaption>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<CodedValuesList
		StoredAttribute="DiffState"
		DisplayAttribute="DiffDescription"
	/>
	<Description><![CDATA[ ]]></Description>
	<Comments><![CDATA[ ]]></Comments>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/Organization/ObjectDiff.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	DTDVersion="05.05.12"
	SurrId="0427389635.Tyler.0000"
	CodedValuesList="False"
	ImageReference=" "
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	XdaConnector="SQL"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	>
	<Attributes>
		<Attribute
			Name="ReposName1"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
		</Attribute>
		<Attribute
			Name="ReposName2"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
		</Attribute>
		<Attribute
			Name="ObjectName1"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
		</Attribute>
		<Attribute
			Name="ObjectName2"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
		</Attribute>
		<Attribute
			Name="ObjectType"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="CodedValuesList"
				CodedValuesList="Valid_ObjectType"
			/>
		</Attribute>
		<Attribute
			Name="DiffComment"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="250"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Description><![CDATA[This will say something like Added to Repos2 or Removed from Repos 2 - or modified (each object will have different criteria, e.g #attrs, lines of code, methods, etc.)]]></Description>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Total_1_Line_Cnt"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[0]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Total_2_Line_Cnt"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[0]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Line_Cnt_Diff"
			PreventUserUpdates="True"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Formula"
				>
				<Formula><![CDATA[ Total_1_Line_Cnt  -  Total_2_Line_Cnt ]]></Formula>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Total_1_Method_Cnt"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[0]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Total_2_Method_Cnt"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[0]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Method_Cnt_Diff"
			PreventUserUpdates="True"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Formula"
				>
				<Formula><![CDATA[ Total_1_Method_Cnt  -  Total_2_Method_Cnt ]]></Formula>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="DiffState"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="12"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA['SAME']]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="CodedValuesList"
				CodedValuesList="List_DiffState"
			/>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="PKObjectDiff"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="ReposName1"
				Descending="False"
			/>
			<Index_Attribute
				Name="ObjectName1"
				Descending="False"
			/>
			<Index_Attribute
				Name="ReposName2"
				Descending="False"
			/>
			<Index_Attribute
				Name="ObjectName2"
				Descending="False"
			/>
			<Index_Attribute
				Name="ObjectType"
				Descending="False"
			/>
		</Index>
	</Indexes>
	<SingularCaption><![CDATA[Object Difference]]></SingularCaption>
	<PluralCaption><![CDATA[Object Differences]]></PluralCaption>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<CodedValuesList
		StoredAttribute=" "
		DisplayAttribute=" "
	/>
	<Description><![CDATA[ObjectDiff is an internal object created and maintained by Java code.  This holds the difference information between 2 objects (DataObject, Attribute, Query, etc)]]></Description>
	<Comments><![CDATA[ ]]></Comments>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/Organization/QueryJoinDataObject.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	SurrId="0417538787.tband.0005"
	CodedValuesList="False"
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	ImageReference=" "
	XdaConnector="SQL"
	DTDVersion="05.05.12"
	>
	<CodedValuesList
		DisplayAttribute=" "
		StoredAttribute=" "
	/>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<SingularCaption><![CDATA[*]]> </SingularCaption>
	<PluralCaption><![CDATA[*]]> </PluralCaption>
	<Description><![CDATA[ These are the relationships used in the specifc QueryObhect (which may be different from the ones in the Repository)]]> </Description>
	<Comments><![CDATA[ ]]> </Comments>
	<Attributes>
		<Attribute
			Name="RepositoryName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="QueryObjectName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="LeftDataObjectName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="RightDataObjectName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="RelationshipName"
			Persistent="True"
			PreventUserUpdates="True"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="100"
			/>
			<Derivation
				DerivationType="Formula"
				>
				<Formula><![CDATA[LeftDataObjectName +'_JN_'+ RightDataObjectName ]]> </Formula>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="JoinType"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="15"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="QueryDataObjPkey"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="RepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="QueryObjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="LeftDataObjectName"
				Descending="False"
			/>
			<Index_Attribute
				Name="RightDataObjectName"
				Descending="False"
			/>
		</Index>
	</Indexes>
</DataObject>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/RuleObjects/RecordSource.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE DataObject SYSTEM "DataObject.dtd">
<DataObject
	SurrId="04424271350052"
	CodedValuesList="False"
	IsRemoteAccessible="False"
	UseQuotedIdentifiers="False"
	SuperClass="DataObject"
	LockMode="AllApplicableAttributes"
	ImageReference=" "
	XdaConnector="SQL"
	DTDVersion="05.05.12"
	>
	<CodedValuesList
		DisplayAttribute=" "
		StoredAttribute=" "
	/>
	<VLSDeployment
		DeploySecurityInfo="False"
	/>
	<SingularCaption><![CDATA[*]]> </SingularCaption>
	<PluralCaption><![CDATA[*]]> </PluralCaption>
	<Description><![CDATA[ A recordSource is mapped to either a DataObject or a QueryObject.  Used to retrieve data from Server to HTML page or Java form.]]> </Description>
	<Comments><![CDATA[ ]]> </Comments>
	<Attributes>
		<Attribute
			Name="RepositoryName"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Repository Name]]></Caption>
		</Attribute>
		<Attribute
			Name="ApplicationName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="100"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Application Name]]></Caption>
		</Attribute>
		<Attribute
			Name="FormName"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="100"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Form Name]]></Caption>
		</Attribute>
		<Attribute
			Name="Attr_Cnt"
			Persistent="True"
			PreventUserUpdates="True"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Count"
				SourceDataObject="RSAttribute(RSAttribute)"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[Number Of Attributes]]></Caption>
		</Attribute>
		<Attribute
			Name="BusinessObject"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="50"
			/>
			<Validation
				ValidationType="Condition"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Caption><![CDATA[Business Object]]></Caption>
		</Attribute>
		<Attribute
			Name="PlacedAttrCnt"
			Persistent="True"
			PreventUserUpdates="True"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Count"
				SourceDataObject="RSAttribute(RSAttribute)"
				>
				<QualificationExpression><![CDATA[isPlaced  = True /* Yes */   ]]> </QualificationExpression>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[Placed Attrbiute Count]]></Caption>
		</Attribute>
		<Attribute
			Name="DisplayedAttrCnt"
			Persistent="True"
			PreventUserUpdates="True"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Count"
				SourceDataObject="RSAttribute(RSAttribute)"
				>
				<QualificationExpression><![CDATA[ isDisplayed  =  True /* Yes */  ]]> </QualificationExpression>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[Displayed Attribute Count]]></Caption>
		</Attribute>
		<Attribute
			Name="ScalarGrid"
			Persistent="True"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			>
			<DataType
				DataType="VarChar"
				Size="10"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA['Scalar']]> </DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[Scalar/Grid]]></Caption>
		</Attribute>
		<Attribute
			Name="AllowInsert"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Boolean"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[false]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="AllowUpdate"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Boolean"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[false]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="AllowDelete"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Boolean"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[false]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="Relationship"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="150"
			/>
		</Attribute>
		<Attribute
			Name="ClassName"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="150"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="RSID"
			PreventUserUpdates="False"
			ValueRequired="True"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				DerivationType="Default"
				>
				<DefaultValue><![CDATA[1]]></DefaultValue>
			</Derivation>
			<Validation
				ValidationType="Condition"
			/>
			<Caption><![CDATA[RecordSource ID]]></Caption>
		</Attribute>
		<Attribute
			Name="TransitionCnt"
			PreventUserUpdates="True"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="Integer"
			/>
			<Derivation
				SourceDataObject="Transition(Transition)"
				DerivationType="Count"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
		<Attribute
			Name="RecordSourceArchetype"
			PreventUserUpdates="False"
			ValueRequired="False"
			LayoutByDefault="True"
			Persistent="True"
			>
			<DataType
				DataType="VarChar"
				Size="250"
			/>
			<Derivation
				DerivationType="None"
			/>
			<Validation
				ValidationType="Condition"
			/>
		</Attribute>
	</Attributes>
	<Indexes>
		<Index
			Name="RecordSourcePkey"
			Primary="True"
			Unique="True"
			IgnoreNulls="False"
			>
			<Index_Attribute
				Name="RepositoryName"
				Descending="False"
			/>
			<Index_Attribute
				Name="ApplicationName"
				Descending="False"
			/>
			<Index_Attribute
				Name="FormName"
				Descending="False"
			/>
			<Index_Attribute
				Name="BusinessObject"
				Descending="False"
			/>
			<Index_Attribute
				Name="RSID"
				Descending="False"
			/>
		</Index>
	</Indexes>
</DataObject>
