=== tylerm007/MetaRepos/Source/Repository.dtd
<!ELEMENT Repository ( DataObjects | QueryObjects | ProcessModels | Relationships | References | JavaApplications  | HTMLApplications  | SourceFiles | Groups)* >
<!ATTLIST Repository
	UseQuotedIdentifiers (True|False) #IMPLIED
	CustomJavaArchetypeDirectory CDATA #IMPLIED
	CustomHTMLArchetypeDirectory CDATA #IMPLIED
	RepositoryVersion CDATA #REQUIRED
	DTDVersion CDATA #REQUIRED
>

<!ELEMENT DataObjects (DataObject)*>
<!ELEMENT QueryObjects (QueryObject)*>
<!ELEMENT ProcessModels (ProcessModel)*>
<!ELEMENT Relationships (Relationship)*>
<!ELEMENT JavaApplications (Application)*>
<!ELEMENT HTMLApplications (Application)*>
<!ELEMENT References (Reference)*>
<!ELEMENT SourceFiles (SourceFile)*>

<!ELEMENT DataObject (#PCDATA)>
<!ELEMENT QueryObject (#PCDATA)>
<!ELEMENT ProcessModel (#PCDATA)>
<!ELEMENT Relationship (#PCDATA)>
<!ELEMENT Application (#PCDATA)>

<!ELEMENT Reference (FileName)*>
<!ATTLIST Reference 
	IsRemote (True|False) #REQUIRED
	Type (VersataVLSClasses|JDKClasses|JavaBeans|CORBAObjects|COMWrapperObjects|JavaClasses|CommonClientandServerClasses|
	ServerClasses|ORBClasses|JavaInterfaceFiles|SwingClasses|EnterpriseJavaBeans) #REQUIRED
>

<!ELEMENT FileName (#PCDATA)>
<!ELEMENT Path (#PCDATA)>


<!ELEMENT SourceFile (FileName | Path | ClassPath )*>
<!ATTLIST SourceFile
	FileType   (DataManager|Interface|Other) #REQUIRED
	PackageName CDATA #IMPLIED
	IsRemoteAccessible (True|False) #IMPLIED
>
<!ELEMENT ClassPath (#PCDATA)>

<!ELEMENT Groups ( Group)*>
<!ELEMENT Group ( Group)*>
<!ATTLIST Group
	Name   CDATA #REQUIRED
>

=== tylerm007/MetaRepos/Source/MetaRepos.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Repository SYSTEM "Repository.dtd">
<Repository
	UseQuotedIdentifiers="False"
	RepositoryVersion="05.05.15"
	DTDVersion="05.05.13"
	>
	<DataObjects>
		<DataObject>DataObjects\RuleObjects\Action</DataObject>
		<DataObject>DataObjects\Root_Objects\Application</DataObject>
		<DataObject>DataObjects\RuleObjects\Attribute</DataObject>
		<DataObject>DataObjects\RuleObjects\Constraint</DataObject>
		<DataObject>DataObjects\Root_Objects\DataObject</DataObject>
		<DataObject>DataObjects\Organization\Object_JN_Group</DataObject>
		<DataObject>DataObjects\Organization\DataObject_Jn_Reln</DataObject>
		<DataObject>DataObjects\RuleObjects\Derivation</DataObject>
		<DataObject>DataObjects\Root_Objects\Form</DataObject>
		<DataObject>DataObjects\Organization\Groups</DataObject>
		<DataObject>DataObjects\RuleObjects\IndexAttr</DataObject>
		<DataObject>DataObjects\RuleObjects\IndexDO</DataObject>
		<DataObject>DataObjects\Validation\List_Derivation</DataObject>
		<DataObject>DataObjects\Organization\QueryDataObject</DataObject>
		<DataObject>DataObjects\Organization\QueryJoinDataObject</DataObject>
		<DataObject>DataObjects\Root_Objects\QueryObject</DataObject>
		<DataObject>DataObjects\RuleObjects\RecordSource</DataObject>
		<DataObject>DataObjects\Root_Objects\Relationship</DataObject>
		<DataObject>DataObjects\Organization\ReposDiff</DataObject>
		<DataObject>DataObjects\Root_Objects\Repository</DataObject>
		<DataObject>DataObjects\Organization\ReposVersion</DataObject>
		<DataObject>DataObjects\RuleObjects\RSAttribute</DataObject>
		<DataObject>DataObjects\RuleObjects\Validation</DataObject>
		<DataObject>DataObjects\Organization\Owner</DataObject>
		<DataObject>DataObjects\Validation\Valid_ObjectType</DataObject>
		<DataObject>DataObjects\Root_Objects\OtherFile</DataObject>
		<DataObject>DataObjects\Root_Objects\ReposName</DataObject>
		<DataObject>DataObjects\Root_Objects\Method</DataObject>
		<DataObject>DataObjects\Organization\ObjectDiff</DataObject>
		<DataObject>DataObjects\RuleObjects\Transition</DataObject>
		<DataObject>DataObjects\Root_Objects\RelationshipRole</DataObject>
		<DataObject>DataObjects\Organization\QueryAttr</DataObject>
		<DataObject>DataObjects\WorkFlow\Template</DataObject>
		<DataObject>DataObjects\WorkFlow\Activity</DataObject>
		<DataObject>DataObjects\CDDMap\Project</DataObject>
		<DataObject>DataObjects\CDDMap\DataObjectMapper</DataObject>
		<DataObject>DataObjects\CDDMap\AttrObjectMapper</DataObject>
		<DataObject>DataObjects\CDDMap\Valid_TransformRule</DataObject>
		<DataObject>DataObjects\Validation\Valid_SQLTypes</DataObject>
		<DataObject>DataObjects\WorkFlow\WFTransition</DataObject>
		<DataObject>DataObjects\Validation\List_DiffState</DataObject>
		<DataObject>DataObjects\Organization\FormObjectDiff</DataObject>
	</DataObjects>
	<QueryObjects>
		<QueryObject>QueryObjects\Qry_AttrFormula</QueryObject>
		<QueryObject>QueryObjects\Qry_AttrParentRepl</QueryObject>
		<QueryObject>QueryObjects\Qry_AttrSum</QueryObject>
		<QueryObject>QueryObjects\Qry_AttrCount</QueryObject>
	</QueryObjects>
	<Relationships>
		<Relationship>DataObjects\REL_Application-Form</Relationship>
		<Relationship>DataObjects\REL_Attribute-Derivation</Relationship>
		<Relationship>DataObjects\REL_Attribute-IndexAttr</Relationship>
		<Relationship>DataObjects\REL_Attribute-Validation</Relationship>
		<Relationship>DataObjects\REL_DataObject-Action</Relationship>
		<Relationship>DataObjects\REL_DataObject-Attribute</Relationship>
		<Relationship>DataObjects\REL_DataObject-Constraint</Relationship>
		<Relationship>DataObjects\REL_DataObject-Object_JN_Group</Relationship>
		<Relationship>DataObjects\REL_DataObject-DataObject_Jn_Reln</Relationship>
		<Relationship>DataObjects\REL_DataObject-Derivation</Relationship>
		<Relationship>DataObjects\REL_DataObject-IndexDO</Relationship>
		<Relationship>DataObjects\REL_DataObject-QueryDataObject</Relationship>
		<Relationship>DataObjects\REL_DataObject-RecordSource</Relationship>
		<Relationship>DataObjects\REL_DataObject-Validation</Relationship>
		<Relationship>DataObjects\REL_Form-RecordSource</Relationship>
		<Relationship>DataObjects\REL_Groups-Object_JN_Group</Relationship>
		<Relationship>DataObjects\REL_Groups-Groups</Relationship>
		<Relationship>DataObjects\REL_IndexDO-IndexAttr</Relationship>
		<Relationship>DataObjects\REL_QueryDataObject-QueryJoinDataObject</Relationship>
		<Relationship>DataObjects\REL_QueryObject-QueryDataObject</Relationship>
		<Relationship>DataObjects\REL_QueryObject-QueryJoinDataObject</Relationship>
		<Relationship>DataObjects\REL_QueryObject-RecordSource</Relationship>
		<Relationship>DataObjects\REL_Relationship-DataObject_Jn_Reln</Relationship>
		<Relationship>DataObjects\REL_Repository-Application</Relationship>
		<Relationship>DataObjects\REL_Repository-DataObject</Relationship>
		<Relationship>DataObjects\REL_Repository-Groups</Relationship>
		<Relationship>DataObjects\REL_Repository-QueryObject</Relationship>
		<Relationship>DataObjects\REL_Repository-Relationship</Relationship>
		<Relationship>DataObjects\REL_Repository-ReposDiff</Relationship>
		<Relationship>DataObjects\REL_ReposVersion-Repository</Relationship>
		<Relationship>DataObjects\REL_Owner-Groups</Relationship>
		<Relationship>DataObjects\REL_QueryDataObject-Object_JN_Group</Relationship>
		<Relationship>DataObjects\REL_Application-Object_JN_Group</Relationship>
		<Relationship>DataObjects\Root_Objects\REL_Repository-OtherFile</Relationship>
		<Relationship>DataObjects\Root_Objects\REL_ReposName-Repository</Relationship>
		<Relationship>DataObjects\Root_Objects\REL_DataObject-Method</Relationship>
		<Relationship>DataObjects\Root_Objects\REL_QueryObject-Method</Relationship>
		<Relationship>DataObjects\Organization\REL_ReposDiff-ObjectDiff</Relationship>
		<Relationship>DataObjects\Root_Objects\REL_Relationship-RelationshipRole</Relationship>
		<Relationship>DataObjects\RuleObjects\REL_RecordSource-RSAttribute</Relationship>
		<Relationship>DataObjects\RuleObjects\REL_RecordSource-Transition</Relationship>
		<Relationship>DataObjects\RuleObjects\REL_Transition-Form</Relationship>
		<Relationship>DataObjects\Organization\REL_QueryDataObject-QueryAttr</Relationship>
		<Relationship>DataObjects\Root_Objects\REL_QueryObject-QueryAttr</Relationship>
		<Relationship>DataObjects\CDDMap\REL_Project-DataObjectMapper</Relationship>
		<Relationship>DataObjects\CDDMap\REL_DataObjectMapper-AttrObjectMapper</Relationship>
		<Relationship>DataObjects\Root_Objects\REL_Repository-DataObjectMapper</Relationship>
		<Relationship>DataObjects\Root_Objects\REL_DataObject-DataObjectMapper</Relationship>
		<Relationship>DataObjects\RuleObjects\REL_Attribute-AttrObjectMapper</Relationship>
		<Relationship>DataObjects\WorkFlow\REL_Template-Activity</Relationship>
		<Relationship>DataObjects\WorkFlow\REL_Activity-WFTransition</Relationship>
		<Relationship>DataObjects\Organization\REL_ObjectDiff-FormObjectDiff</Relationship>
	</Relationships>
	<HTMLApplications>
		<Application>Project1</Application>
		<Application>HTML_ReposMaint</Application>
	</HTMLApplications>
	<SourceFiles>
		<SourceFile
			FileType="Other"
			PackageName="MetaRepos"
			IsRemoteAccessible="False"
			>
			<FileName><![CDATA[DataObjects\JavaExtensions\BSD_DataObject.java]]></FileName>
			<Path><![CDATA[]]></Path>
			<ClassPath><![CDATA[]]></ClassPath>
		</SourceFile>
	</SourceFiles>
	<Groups>
		<Group
			Name="DataObjects"
			>
			<Group
				Name="Root_Objects"
			/>
			<Group
				Name="RuleObjects"
			/>
			<Group
				Name="Organization"
			/>
			<Group
				Name="Validation"
			/>
			<Group
				Name="JavaExtensions"
			/>
			<Group
				Name="WorkFlow"
			/>
			<Group
				Name="CDDMap"
			/>
		</Group>
		<Group
			Name="QueryObjects"
		/>
	</Groups>
	<JavaApplications>
		<Application>JavaSample</Application>
		<Application>CommonDataDict</Application>
		<Application>ObjectDiff</Application>
	</JavaApplications>
</Repository>
