=== tylerm007/MetaRepos/Source/VLS/DataObjects/WorkFlow/Relation.dtd
<!ELEMENT Relationships ( Relationship )* >
<!ATTLIST Relationships
	DTDVersion CDATA #REQUIRED
>

<!ELEMENT Relationship ( AttributePairs | AscendCaption | DescendCaption | ErrPreventInsertOrUpdateChild | ErrPreventDeleteParent | ErrPreventUpdateParent |ExtendedProperties |HiddenProperties )* >
<!ATTLIST Relationship 

	CountAggregates CDATA #IMPLIED
	CountReplicates CDATA #IMPLIED
	OnParentUpdate (PreventIfChildren|UpdateChildren) #IMPLIED
	OnParentDelete (PreventIfChildren|DeleteChildren|NullChildrenForeignKey) #IMPLIED
	IsEnforce (True|False) #REQUIRED 
	OnChildInsertOrUpdate (PreventIfNoParent|InsertParentIfNone) #IMPLIED
	ChildRoleName CDATA #IMPLIED
	ParentRoleName CDATA #IMPLIED
	ParentAttributeGroupInstance CDATA #IMPLIED
	ChildAttributeGroupInstance CDATA #IMPLIED

>

<!ELEMENT AttributePairs (AttributePair)* >
<!ELEMENT AttributePair EMPTY >
<!ATTLIST AttributePair
	ParentAttribute CDATA #REQUIRED
	ChildAttribute CDATA #REQUIRED
>
<!ELEMENT AscendCaption (#PCDATA)> 
<!ELEMENT DescendCaption (#PCDATA)>
<!ELEMENT ErrPreventInsertOrUpdateChild (#PCDATA)>
<!ELEMENT ErrPreventDeleteParent (#PCDATA)>
<!ELEMENT ErrPreventUpdateParent (#PCDATA)>

<!ELEMENT ExtendedProperties (Property)* >
<!ELEMENT HiddenProperties (Property)* >
<!ELEMENT Property EMPTY >
<!ATTLIST Property 
	Name CDATA #REQUIRED
	Value CDATA #REQUIRED
>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_QueryObject-QueryJoinDataObject.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		CountAggregates="1"
		CountReplicates="0"
		ChildRoleName="QueryJoinDataObjects"
		ParentRoleName="QueryObject1"
		>
		<AscendCaption><![CDATA[QueryObject]]> </AscendCaption>
		<DescendCaption><![CDATA[QueryJoinDataObject(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="QueryObjectName"
				ChildAttribute="QueryObjectName"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/Organization/REL_ObjectDiff-FormObjectDiff.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		ParentRoleName="ObjectDiff"
		ChildRoleName="FormObjectDiff"
		IsEnforce="True"
		OnParentDelete="DeleteChildren"
		>
		<AttributePairs>
			<AttributePair
				ParentAttribute="ReposName1"
				ChildAttribute="ReposName1"
			/>
			<AttributePair
				ParentAttribute="ObjectName1"
				ChildAttribute="AppName1"
			/>
			<AttributePair
				ParentAttribute="ReposName2"
				ChildAttribute="ReposName2"
			/>
			<AttributePair
				ParentAttribute="ObjectName2"
				ChildAttribute="AppName2"
			/>
			<AttributePair
				ParentAttribute="ObjectType"
				ChildAttribute="ObjectType"
			/>
		</AttributePairs>
		<AscendCaption><![CDATA[Object Difference]]></AscendCaption>
		<DescendCaption><![CDATA[Object Differences]]></DescendCaption>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]></ErrPreventUpdateParent>
		<ErrPreventDeleteParent><![CDATA[<System Supplied>]]></ErrPreventDeleteParent>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]></ErrPreventInsertOrUpdateChild>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_IndexDO-IndexAttr.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		CountAggregates="0"
		CountReplicates="0"
		ChildRoleName="IndexAttrs"
		ParentRoleName="MyIndex"
		>
		<AscendCaption><![CDATA[IndexDO]]> </AscendCaption>
		<DescendCaption><![CDATA[IndexAttr(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="DataObjectName"
				ChildAttribute="DataObjectName"
			/>
			<AttributePair
				ParentAttribute="IndexName"
				ChildAttribute="IndexName"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_Attribute-Validation.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="InsertParentIfNone"
		CountAggregates="1"
		CountReplicates="0"
		ChildRoleName="Validations"
		ParentRoleName="ValidationAttr"
		>
		<AscendCaption><![CDATA[Attribute]]> </AscendCaption>
		<DescendCaption><![CDATA[Validation(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="DataObjectName"
				ChildAttribute="DataObjectName"
			/>
			<AttributePair
				ParentAttribute="AttrName"
				ChildAttribute="AttrName"
			/>
		</AttributePairs>
	</Relationship>
	<Relationship
		IsEnforce="False"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="PreventIfChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		CountAggregates="0"
		CountReplicates="0"
		ParentRoleName="Attribute2"
		ChildRoleName="Validation"
		>
		<AscendCaption><![CDATA[*]]> </AscendCaption>
		<DescendCaption><![CDATA[*]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[<System Supplied>]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="DataObjectName"
				ChildAttribute="CodedValueList"
			/>
			<AttributePair
				ParentAttribute="AttrName"
				ChildAttribute="AttrName"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_Application-Form.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		CountAggregates="6"
		CountReplicates="1"
		ChildRoleName="Forms"
		ParentRoleName="MyApplication"
		>
		<AscendCaption><![CDATA[Application]]> </AscendCaption>
		<DescendCaption><![CDATA[Form(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="ApplicationName"
				ChildAttribute="ApplicationName"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/RuleObjects/REL_RecordSource-Transition.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		ParentRoleName="RecordSource"
		ChildRoleName="Transition"
		IsEnforce="True"
		OnParentDelete="DeleteChildren"
		CountAggregates="1"
		>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="ApplicationName"
				ChildAttribute="ApplicationName"
			/>
			<AttributePair
				ParentAttribute="FormName"
				ChildAttribute="FormName"
			/>
			<AttributePair
				ParentAttribute="BusinessObject"
				ChildAttribute="BusinessObject"
			/>
			<AttributePair
				ParentAttribute="RSID"
				ChildAttribute="RSID"
			/>
		</AttributePairs>
		<AscendCaption><![CDATA[RecordSource]]></AscendCaption>
		<DescendCaption><![CDATA[Transition(s)]]></DescendCaption>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]></ErrPreventUpdateParent>
		<ErrPreventDeleteParent><![CDATA[<System Supplied>]]></ErrPreventDeleteParent>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]></ErrPreventInsertOrUpdateChild>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_ReposVersion-Repository.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="InsertParentIfNone"
		CountAggregates="0"
		CountReplicates="0"
		ChildRoleName="Repositories"
		ParentRoleName="Version"
		>
		<AscendCaption><![CDATA[ReposVersion]]> </AscendCaption>
		<DescendCaption><![CDATA[Repository(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="Version"
				ChildAttribute="RepositoryVersion"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_Repository-ReposDiff.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		CountAggregates="0"
		CountReplicates="9"
		ChildRoleName="ReposDiff1"
		ParentRoleName="ReposSource"
		>
		<AscendCaption><![CDATA[Repository]]> </AscendCaption>
		<DescendCaption><![CDATA[ReposDiff(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="ReposName1"
			/>
		</AttributePairs>
	</Relationship>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		CountAggregates="0"
		CountReplicates="9"
		ChildRoleName="ReposDiff2"
		ParentRoleName="ReposSource2"
		>
		<AscendCaption><![CDATA[Repository]]> </AscendCaption>
		<DescendCaption><![CDATA[ReposDiff(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="ReposName2"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>
