=== tylerm007/MetaRepos/Source/VLS/DataObjects/WorkFlow/Relation.dtd
<!ELEMENT Relationships ( Relationship )* >
<!ATTLIST Relationships
	DTDVersion CDATA #REQUIRED
>

<!ELEMENT Relationship ( AttributePairs | AscendCaption | DescendCaption | ErrPreventInsertOrUpdateChild | ErrPreventDeleteParent | ErrPreventUpdateParent |ExtendedProperties |HiddenProperties )* >
<!ATTLIST Relationship 

	CountAggregates CDATA #IMPLIED
	CountReplicates CDATA #IMPLIED
	OnParentUpdate (PreventIfChildren|UpdateChildren) #IMPLIED
	OnParentDelete (PreventIfChildren|DeleteChildren|NullChildrenForeignKey) #IMPLIED
	IsEnforce (True|False) #REQUIRED 
	OnChildInsertOrUpdate (PreventIfNoParent|InsertParentIfNone) #IMPLIED
	ChildRoleName CDATA #IMPLIED
	ParentRoleName CDATA #IMPLIED
	ParentAttributeGroupInstance CDATA #IMPLIED
	ChildAttributeGroupInstance CDATA #IMPLIED

>

<!ELEMENT AttributePairs (AttributePair)* >
<!ELEMENT AttributePair EMPTY >
<!ATTLIST AttributePair
	ParentAttribute CDATA #REQUIRED
	ChildAttribute CDATA #REQUIRED
>
<!ELEMENT AscendCaption (#PCDATA)> 
<!ELEMENT DescendCaption (#PCDATA)>
<!ELEMENT ErrPreventInsertOrUpdateChild (#PCDATA)>
<!ELEMENT ErrPreventDeleteParent (#PCDATA)>
<!ELEMENT ErrPreventUpdateParent (#PCDATA)>

<!ELEMENT ExtendedProperties (Property)* >
<!ELEMENT HiddenProperties (Property)* >
<!ELEMENT Property EMPTY >
<!ATTLIST Property 
	Name CDATA #REQUIRED
	Value CDATA #REQUIRED
>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_Groups-Groups.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		CountAggregates="0"
		CountReplicates="0"
		ChildRoleName="Groups"
		ParentRoleName="MyGroup"
		>
		<AscendCaption><![CDATA[Group]]> </AscendCaption>
		<DescendCaption><![CDATA[Group(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="ParentRepositoryName"
			/>
			<AttributePair
				ParentAttribute="GroupName"
				ChildAttribute="ParentGroupName"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_RecordSource-RSAttribute.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		CountAggregates="3"
		CountReplicates="0"
		ChildRoleName="RSAttrs"
		ParentRoleName="MyRecorfdSource"
		>
		<AscendCaption><![CDATA[RecordSource]]> </AscendCaption>
		<DescendCaption><![CDATA[RSAttribute(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="ApplicationName"
				ChildAttribute="ApplicationName"
			/>
			<AttributePair
				ParentAttribute="FormName"
				ChildAttribute="FormName"
			/>
			<AttributePair
				ParentAttribute="BusinessObject"
				ChildAttribute="BusinessObject"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_DataObject-DataObject_Jn_Reln.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		CountAggregates="2"
		CountReplicates="0"
		ChildRoleName="AllRelationships"
		ParentRoleName="DataObject"
		>
		<AscendCaption><![CDATA[DataObject]]> </AscendCaption>
		<DescendCaption><![CDATA[DataObject_Jn_Reln(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[ ]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="DataObjectName"
				ChildAttribute="DataObjectName"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_DataObject-IndexDO.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		CountAggregates="0"
		CountReplicates="0"
		ChildRoleName="Indexes"
		ParentRoleName="DataObjectOfIndex"
		>
		<AscendCaption><![CDATA[DataObject]]> </AscendCaption>
		<DescendCaption><![CDATA[IndexDO(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="DataObjectName"
				ChildAttribute="DataObjectName"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>
