=== tylerm007/MetaRepos/Source/VLS/DataObjects/WorkFlow/Relation.dtd
<!ELEMENT Relationships ( Relationship )* >
<!ATTLIST Relationships
	DTDVersion CDATA #REQUIRED
>

<!ELEMENT Relationship ( AttributePairs | AscendCaption | DescendCaption | ErrPreventInsertOrUpdateChild | ErrPreventDeleteParent | ErrPreventUpdateParent |ExtendedProperties |HiddenProperties )* >
<!ATTLIST Relationship 

	CountAggregates CDATA #IMPLIED
	CountReplicates CDATA #IMPLIED
	OnParentUpdate (PreventIfChildren|UpdateChildren) #IMPLIED
	OnParentDelete (PreventIfChildren|DeleteChildren|NullChildrenForeignKey) #IMPLIED
	IsEnforce (True|False) #REQUIRED 
	OnChildInsertOrUpdate (PreventIfNoParent|InsertParentIfNone) #IMPLIED
	ChildRoleName CDATA #IMPLIED
	ParentRoleName CDATA #IMPLIED
	ParentAttributeGroupInstance CDATA #IMPLIED
	ChildAttributeGroupInstance CDATA #IMPLIED

>

<!ELEMENT AttributePairs (AttributePair)* >
<!ELEMENT AttributePair EMPTY >
<!ATTLIST AttributePair
	ParentAttribute CDATA #REQUIRED
	ChildAttribute CDATA #REQUIRED
>
<!ELEMENT AscendCaption (#PCDATA)> 
<!ELEMENT DescendCaption (#PCDATA)>
<!ELEMENT ErrPreventInsertOrUpdateChild (#PCDATA)>
<!ELEMENT ErrPreventDeleteParent (#PCDATA)>
<!ELEMENT ErrPreventUpdateParent (#PCDATA)>

<!ELEMENT ExtendedProperties (Property)* >
<!ELEMENT HiddenProperties (Property)* >
<!ELEMENT Property EMPTY >
<!ATTLIST Property 
	Name CDATA #REQUIRED
	Value CDATA #REQUIRED
>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_Repository-Application.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		CountAggregates="4"
		CountReplicates="1"
		ChildRoleName="Applications"
		ParentRoleName="AppRepos"
		>
		<AscendCaption><![CDATA[Repository]]> </AscendCaption>
		<DescendCaption><![CDATA[Application(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/Root_Objects/REL_DataObject-Method.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		ParentRoleName="ThisDataObject"
		ChildRoleName="DataMethods"
		IsEnforce="False"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="DataObjectName"
				ChildAttribute="ObjectName"
			/>
		</AttributePairs>
		<AscendCaption><![CDATA[DataObject]]></AscendCaption>
		<DescendCaption><![CDATA[Method(s)]]></DescendCaption>
		<ErrPreventUpdateParent><![CDATA[]]></ErrPreventUpdateParent>
		<ErrPreventDeleteParent><![CDATA[]]></ErrPreventDeleteParent>
		<ErrPreventInsertOrUpdateChild><![CDATA[]]></ErrPreventInsertOrUpdateChild>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_Attribute-Derivation.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="InsertParentIfNone"
		CountAggregates="5"
		CountReplicates="0"
		ChildRoleName="Derivations"
		ParentRoleName="DerivationAttr"
		>
		<AscendCaption><![CDATA[Attribute]]> </AscendCaption>
		<DescendCaption><![CDATA[Derivation(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="DataObjectName"
				ChildAttribute="DataObjectName"
			/>
			<AttributePair
				ParentAttribute="AttrName"
				ChildAttribute="AttrName"
			/>
		</AttributePairs>
	</Relationship>
	<Relationship
		IsEnforce="False"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="PreventIfChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		CountAggregates="0"
		CountReplicates="0"
		ParentRoleName="Attribute"
		ChildRoleName="Derivation"
		>
		<AscendCaption><![CDATA[*]]> </AscendCaption>
		<DescendCaption><![CDATA[*]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[<System Supplied>]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="DataObjectName"
				ChildAttribute="SourceDataObject"
			/>
			<AttributePair
				ParentAttribute="AttrName"
				ChildAttribute="AttrName"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_Repository-DataObject.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="InsertParentIfNone"
		CountAggregates="4"
		CountReplicates="0"
		ChildRoleName="DataObjects"
		ParentRoleName="Repository"
		>
		<AscendCaption><![CDATA[Repository]]> </AscendCaption>
		<DescendCaption><![CDATA[DataObject(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_DataObject-Constraint.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="InsertParentIfNone"
		CountAggregates="1"
		CountReplicates="0"
		ChildRoleName="Constraints"
		ParentRoleName="ConstraintRepository"
		>
		<AscendCaption><![CDATA[DataObject]]> </AscendCaption>
		<DescendCaption><![CDATA[Constraint(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="DataObjectName"
				ChildAttribute="DataObjectName"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_Groups-Object_JN_Group.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="True"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		CountAggregates="0"
		CountReplicates="0"
		ChildRoleName="DataObject_JN_Groups1"
		ParentRoleName="Group"
		>
		<AscendCaption><![CDATA[Group]]> </AscendCaption>
		<DescendCaption><![CDATA[DataObject_JN_Group(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="GroupName"
				ChildAttribute="GroupName"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/REL_DataObject-Derivation.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		IsEnforce="False"
		OnParentUpdate="PreventIfChildren"
		OnParentDelete="DeleteChildren"
		OnChildInsertOrUpdate="PreventIfNoParent"
		CountAggregates="0"
		CountReplicates="0"
		ChildRoleName="Derivations1"
		ParentRoleName="SourceDataObject_1"
		>
		<AscendCaption><![CDATA[DataObject]]> </AscendCaption>
		<DescendCaption><![CDATA[Derivation(s)]]> </DescendCaption>
		<ErrPreventInsertOrUpdateChild><![CDATA[]]> </ErrPreventInsertOrUpdateChild>
		<ErrPreventDeleteParent><![CDATA[]]> </ErrPreventDeleteParent>
		<ErrPreventUpdateParent><![CDATA[]]> </ErrPreventUpdateParent>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="DataObjectName"
				ChildAttribute="SourceDataObject"
			/>
		</AttributePairs>
	</Relationship>
</Relationships>

=== tylerm007/MetaRepos/Source/VLS/DataObjects/Root_Objects/REL_Relationship-RelationshipRole.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Relationships SYSTEM "Relation.dtd">
<Relationships
	DTDVersion="05.05.12"
	>
	<Relationship
		ParentRoleName="Relationship"
		ChildRoleName="RelationshipRole"
		IsEnforce="True"
		OnParentDelete="DeleteChildren"
		CountAggregates="1"
		>
		<AttributePairs>
			<AttributePair
				ParentAttribute="RepositoryName"
				ChildAttribute="RepositoryName"
			/>
			<AttributePair
				ParentAttribute="RelationshipName"
				ChildAttribute="RelationshipName"
			/>
			<AttributePair
				ParentAttribute="ParentDOName"
				ChildAttribute="ParentDOName"
			/>
			<AttributePair
				ParentAttribute="ChildDOName"
				ChildAttribute="ChildDOName"
			/>
		</AttributePairs>
		<AscendCaption><![CDATA[Relationship]]></AscendCaption>
		<DescendCaption><![CDATA[Roles]]></DescendCaption>
		<ErrPreventUpdateParent><![CDATA[<System Supplied>]]></ErrPreventUpdateParent>
		<ErrPreventDeleteParent><![CDATA[<System Supplied>]]></ErrPreventDeleteParent>
		<ErrPreventInsertOrUpdateChild><![CDATA[<System Supplied>]]></ErrPreventInsertOrUpdateChild>
	</Relationship>
</Relationships>
